### PR TITLE
Div on CPU

### PR DESCRIPTION
**Pull request by gallanoe**

### CODE REVIEW

**Comment by gallanoe** [comment]
Checks only pass when eps. value for numerical stability is removed due to how test is written. Should we update test to reflect concerns for numerical stability?

**Comment by geohot** [comment]
Can you fix tabs and remove the other div?

**Comment by geohot** [comment]
Actually wait, does the other div work fine, and the test is just bad because I don't fix 0?

**Comment by gallanoe** [comment]
AFAIK, numpy does not handle numerical stability under the hood (may be very wrong on this), so we'd need to explicitly add eps to our testing. However, div w/ epsilon leads BN2D to fail test. Finally, while old implementation definitely takes fewer lines of code, the new implementation is 5x faster in the forward pass at 1.8x faster in the backward pass.

**Pull request merged**
