### PR TITLE
A Triton backend for tinygrad

### PR DESCRIPTION
**Pull request by geohot**
Works to add numbers, more soon.

@ptillet is there a way to not use torch for the buffers and instead use something like pycuda?

### CODE REVIEW

**Comment by ptillet** [comment]
Hey! The JIT is loosely tied to pytorch in two different ways right now:
- we use pytorch to get the current stream. You could redefine https://github.com/openai/triton/blob/main/python/triton/runtime/jit.py#L21 to bypass torch if you already have a stream handle available. 
- kernel arguments that have a `data_ptr` methods are casted to pointers and their dtype is used to specialize the kernel.  If you wrap pycuda pointers in an object that can also return a datatype (https://github.com/openai/triton/blob/main/python/triton/runtime/jit.py#L425-L436) then this should work.

That said, given the scope at which tinygrad operates, I believe you may benefit from using the `triton.compile` API (https://github.com/openai/triton/blob/main/python/triton/compiler.py#L1442), which returns a very thin wrapper that accepts raw CUDA pointers and has very little overhead. This is what the Triton JIT uses internally https://github.com/openai/triton/blob/main/python/triton/runtime/jit.py#L266-L285

**Comment by geohot** [comment]
Thanks for the quick reply!

Yea, I'm realizing this with the JIT too. I should write a transformer at the "ast" stage I think from the tinygrad AST instead of trying to output Python code.

Do you think I should base things off 1.1, what's in main branch (2.0?), or does it not matter? I remember you talking about doing a big rewrite.

**Comment by ptillet** [comment]
I think you should base things off the latest master branch. The rewrite is complete. We are working through some remaining performance regression issues but we plan to release a 2.0alpha in a couple of weeks

**Comment by geohot** [comment]
Thanks @martinloretzzz for the fixups!

 I think once all tests pass for triton backend we can upstream. There's more than the ops tests.

**Pull request merged**
