### PR TITLE
less than 1000 lines

### LINKED ISSUE #21: tinygrad is growing! should be tiny! add CI test for < 1000 lines
I deleted all the fastconv crap because it wasn't tiny. Output from sloccount:

```
SLOC    Directory       SLOC-by-Language (Sorted)
325     tinygrad        python=325
260     test            python=260


Totals grouped by language (dominant language first):
python:         585 (100.00%)
```

Can someone add sloccount to CI and have it fail if it ever gets above 1000?

Also, no code golf, but refactors that reduce complexity are very welcome.

### PR DESCRIPTION
**Pull request by Liamdoult**
Elegant solution turned to shit and saved at the last second.

Closes #21

### CODE REVIEW

**Comment by alex-eyre** [comment]
that sed is some voodoo fuckery i'm impressed, I just chained `cut`, `grep` and `xargs` lol

**Comment by Liamdoult** [comment]
> that sed is some voodoo fuckery i'm impressed, I just chained `cut`, `grep` and `xargs` lol

That's regex

**Comment by geohot** [comment]
Wow! 2 PRs (#23 and #24), each 12 lines, both very similar. How shall I choose?

**Comment by Liamdoult** [comment]
@geohot Mine was 1 minute quicker!

**Comment by geohot** [comment]
Omg they even both run in 12s. Choosing this one because apt > npm.

**Comment by Liamdoult** [comment]
🎉

**Comment by alex-eyre** [comment]
> Omg they even both run in 12s. Choosing this one because apt > npm.
yeah I was pretty taken aback we submitted prs within like 60s of each other --- fair enough about npm it's bloat central

**Pull request merged**
