### PR TITLE
Cleanup yolo and remove stateless classes

### PR DESCRIPTION
**Pull request by jla524**

### CODE REVIEW

**Comment by geohot** [comment]
Is yolo small enough to have a CI test for?

**Comment by jla524** [comment]
The weights may take a while to load, but let me give it a try

**Comment by jla524** [comment]
The confidence of one of the predictions is much lower on the CI server. I'm getting over 90% on my machine, and around 55% on the server. I guess it has something to do with the dependencies. But the test is passing now.

**Comment by geohot** [comment]
Looks good, merging!

**Pull request merged**
