### PR TITLE
Accel/cuda

### PR DESCRIPTION
**Pull request by Adrianbakke**
test_ops pass, but needs a little cleaning before good

### CODE REVIEW

**Comment by geohot** [comment]
Cool! Be careful around changes to the main code, everything outside accel/cuda/ops_cuda, but cleaned up this should be good to merge.

**Comment by Adrianbakke** [comment]
Cleaned up and also made the reduce op faster.

Happy with this for now, tell me if you want something changed

**Comment by geohot** [comment]
Will merge if tests pass!

**Comment by geohot** [comment]
If you are still interested in this, check out my refactor of ops_gpu.py into ops_gpu.py and llops/gpu.py

I think you could refactor to move CUDA to llops/cuda.py and use ops_gpu.py for a lot of the boilerplate.

**Comment by Adrianbakke** [comment]
cool, will take a look

**Pull request merged**
