### PR TITLE
Detach

### PR DESCRIPTION
**Pull request by adamritter**

### CODE REVIEW

**Comment by adamritter** [comment]
It's not clearly documented whether Tensor data is guaranteed to be immutable or not.
    return Tensor(self.data, self.gpu) may be enough. Also if data is guaranteed to be immutable, reshape GPU implementation should be simpler (identity unary operation on a buffer doesn't make sense).

**Comment by geohot** [comment]
Can you fix test? (even if you didn't break it)

**Comment by marcelbischoff** [comment]
also how about adding it to `test_mnist.py`?

**Comment by adamritter** [comment]
> also how about adding it to `test_mnist.py`?

I just saw that your code and MNIST already only stores the data from the loss, so that's not the problem with the training :(

I wanted to try your fork, but it was looking for /Users/marcel/Downloads/train/, and I was lazy to download the data by hand

**Comment by marcelbischoff** [comment]
> > also how about adding it to `test_mnist.py`?
> 
> I just saw that your code and MNIST already only stores the data from the loss, so that's not the problem with the training :(
> 
> I wanted to try your fork, but it was looking for /Users/marcel/Downloads/train/, and I was lazy to download the data by hand
```
pip install kaggle
kaggle competitions download -c dogs-vs-cats
```

**Comment by adamritter** [comment]
This is so strange that the test setup stopped working (the system can't install pyopencl)

**Comment by marcelbischoff** [comment]
I saw that. Did the version change?

**Comment by dustcollector12** [comment]
I am also wondering what's wrong. I don't have any tests failing locally.

**Comment by adamritter** [comment]
I have no idea, maybe a package changed, it needs to be debugged :(

**Comment by big-c-note** [comment]
I pip installed pyopencl yesterday. `pip freeze` shows:

```pyopencl==2020.2.2```

https://pypi.org/project/pyopencl/ shows we're on 2020.3 now.

requirements.txt doesn't require aversion. Quick fix is changing to:

```pyopencl==2020.2.2```

Theoretically, I'm not sure how the tests are set up.

**Comment by big-c-note** [comment]
And, trying to install new pyopencl locally and I get the same error as the test suite. So, maybe let's switch to version numbers. I'll make a quick PR.

**Comment by adamritter** [comment]
Sure, thanks! Maybe we should report the problem to pyopencl devs as well

**Comment by big-c-note** [comment]
I did. See PR I just made with issue #

**Pull request merged**
