### PR TITLE
refactor context manager

### PR DESCRIPTION
**Pull request by ductm104**
Using [PEP 448](https://peps.python.org/pep-0448/) to merge dicts.
```python
>>> {**{'x': 1}, **{'x': 2}}
{'x': 2}
```

### CODE REVIEW

**Comment by ductm104** [comment]
Idk, what tests should I write?

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/helpers.py                        2               2
------------------------------------------------------------
lines added in the tinygrad folder: 0
```

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/helpers.py                        2               2
------------------------------------------------------------
lines added in the tinygrad folder: 0
```

**Comment by geohot** [comment]
Unit tests that confirm the correct behavior

**Comment by ductm104** [comment]
i'll close this, will reopen when add tests.

**Pull request closed without merging**
