### PR TITLE
fix pyopencl

### PR DESCRIPTION
**Pull request by big-c-note**
Seeing if tests pass with fixed pyopencl version. Not entirely sure how test suite works but guessing we're pip installing newest version

### CODE REVIEW

**Comment by big-c-note** [comment]
Works. New version of pyopenl issue. I'll open an issue for them

**Comment by adamritter** [comment]
https://github.com/inducer/pyopencl/issues/404

They already have (since 12 minutes ago)

**Comment by adamritter** [comment]
Ah sorry, that was you :) I shouldn't write comments at night from my phone

**Comment by big-c-note** [comment]
woot on the board

**Pull request merged**
