### PR TITLE
Remove usage of `isinstance` in the codebase + various optimizations

### LINKED ISSUE #810: Crusade against `isinstance`
Many calls to the expensive function `isinstance` in various hot paths. In the majority of cases we can avoid those calls using inheritance or single-dispatch.

Should be a significant speed up if we manage to eliminate most of them.

### PR DESCRIPTION
**Pull request by rayanht**
# Summary

Remove the overwhelming majority of `isinstance` calls in favor of `x.__class__` comparisons. Closes #810 

# Test Plan

## Correctness

Local test suite is passing. Wait for CI

## Performance

`test_net_speed.py` benchmark:

### Before

```
test/test_net_speed.py::TestConvSpeed::test_mnist torch forward pass:  19.182 ms
torch backward pass: 19.889 ms
         362545 function calls (351966 primitive calls) in 234.580 seconds

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        5   12.607    2.521   12.832    2.566 ops_gpu.py:44(_copyin)
     1142   12.266    0.011   42.102    0.037 symbolic.py:59(sum)
    55734    8.959    0.000    8.959    0.000 {built-in method builtins.isinstance} <<<<<<<<<<<<<
    11876    7.671    0.001   18.786    0.002 symbolic.py:30(__mul__)
8036/4978    6.373    0.001   11.315    0.002 symbolic.py:15(render)
    10086    5.861    0.001    9.720    0.001 symbolic.py:128(__init__)
       16    5.621    0.351    5.621    0.351 {built-in method io.open}
      791    5.115    0.006   34.018    0.043 shapetracker.py:185(reshape)
     1845    4.884    0.003    7.792    0.004 shapetracker.py:33(__init__)
   910/20    4.742    0.005  139.127    6.956 lazy.py:107(realize)

forward pass:  16.117 ms, 0.84x off baseline 19.182 ms
backward pass: 31.474 ms, 1.58x off baseline 19.889 ms
```

### After

```
test/test_net_speed.py::TestConvSpeed::test_mnist torch forward pass:  24.423 ms
torch backward pass: 22.493 ms
         362565 function calls (351986 primitive calls) in 230.995 seconds

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1142   11.326    0.010   39.657    0.035 symbolic.py:59(sum)
       16   10.550    0.659   10.550    0.659 {built-in method io.open}
    11876    7.674    0.001   19.093    0.002 symbolic.py:30(__mul__)
    10086    5.659    0.001    9.878    0.001 symbolic.py:125(__init__)
      791    5.268    0.007   33.978    0.043 shapetracker.py:185(reshape)
        5    4.744    0.949    4.989    0.998 ops_gpu.py:44(_copyin)
   910/20    4.502    0.005  129.745    6.487 lazy.py:107(realize)
     1845    4.359    0.002    7.340    0.004 shapetracker.py:33(__init__)
     9488    3.937    0.000    3.937    0.000 symbolic.py:148(get_bounds)
5371/2313    3.654    0.001    6.735    0.003 symbolic.py:15(render)
1190/1025    3.564    0.003   64.799    0.063 lazy.py:187(movement_op)
     9470    3.297    0.000    3.835    0.000 symbolic.py:119(create_node)
  1680/80    3.140    0.002    9.021    0.113 dataclasses.py:1280(_asdict_inner)
     6670    3.123    0.000    4.752    0.001 {built-in method builtins.sum}
    11150    2.980    0.000    2.980    0.000 shapetracker.py:34(<genexpr>)
    [...]
     6520    1.179    0.000    1.179    0.000 {built-in method builtins.isinstance} <<<<<<<<<<<<<<<<


forward pass:  13.977 ms, 0.72x off baseline 19.368 ms
backward pass: 30.803 ms, 1.55x off baseline 19.827 ms
```

We save roughly `50,000` calls to `isinstance`

### CODE REVIEW

**Comment by rayanht** [comment]
Not ready for review yet, the changes make `mypy` very angry + i'm getting a lot of variance on the performance improvement figures.

@geohot do we have a more disciplined approach to measuring perf rather than eyeballing this test case?

**Comment by geohot** [comment]
So the LLaMA bounty mentioned in the issue is a great one, much more real world than this.

Not really, what did you have in mind? Like microbenchmarks?

**Comment by YurySolovyov** [comment]
Can linter be made to catch isinstance usage for future cases? To discourage it that is

**Comment by rayanht** [comment]
@YurySolovyov yeah we should probably add a rule for that if I manage to consistently show a perf improvement, right now it's a bit unclear

@geohot my bad I hadn't seen that you replied to the issue, i guess that works yeah, much more representative

**Comment by geohot** [comment]
If it's close to a wash, I like isinstance better. The code should really be rethought to not need it, like what you did with Symbolic.

The LLaMA stuff is very representative, but I think a microbenchmark test suite might help to find bottlenecks and regressions.

**Comment by rayanht** [comment]
Hey @geohot I got sidetracked and did a bunch of adhoc optimizations that shaved 300ms of runtime for LLaMa on my Mac M1 (800 -> 500). Would you mind running your bounty benchmark on this rev just so I can have an idea of whether or not this had considerable effects on your machine?

Probably won't end up proposing this as a single PR because there's too many unrelated things going on but curious to see if it had an actually had an effect

**Comment by geohot** [comment]
450 -> 400 on my machine

**Comment by rayanht** [comment]
hmmm experimenting with some stuff, is it worth it to make `forward` slower if we can make `backward` significantly faster?

Before

```
forward pass:  16.117 ms, 0.84x off baseline 19.182 ms
backward pass: 31.474 ms, 1.58x off baseline 19.889 ms
```

That gives us forward + backward 47.5ms vs. forward + backward baseline 38ms

After

```
forward pass:  12.946 ms, 1.08x off baseline 11.985 ms
backward pass: 28.348 ms, 0.96x off baseline 29.438 ms
```

Which gives us forward + backward 41ms vs. forward + backward baseline 40ms

**Comment by geohot** [comment]
In general no. Many models (like LLaMA) never run a backward pass.

**Comment by rayanht** [comment]
in the general case though is that tradeoff not worth it?

or is the vision that tinygrad is more about fast inference than fast training?

**Comment by geohot** [comment]
That tradeoff is never worth it. For training, you almost always will be using the JIT, not true for inference.

**Comment by rayanht** [comment]
Huh actually i completely hallucinated the tradeoff, I hadn't re-measured "before" in a while; seems like baseline in now _way_ faster than what it was in the "after" of my previous PR. Not too sure what changed in the repo and/or my machine to cause that

As of commit `606b841` on master we have

Before:

```
forward pass:  17.704 ms, 1.51x off baseline 11.763 ms
backward pass: 32.777 ms, 1.16x off baseline 28.181 ms
```

After:

```
forward pass:  15.735 ms, 1.13x off baseline 13.958 ms
backward pass: 29.791 ms, 0.87x off baseline 34.291 ms
```

So we're actually in profit, no tradeoffs

**Comment by rayanht** [comment]
## Update

First sighting of sub 200ms on M1, I think i've exhausted all the cheap tricks; getting the next 100ms down is all about some actual refactoring

```
loaded weights in 9349.01 ms, 13.48 GB loaded at 1.44 GB/s
Hello.
ran model in 4482.44 ms
sync in 6.21 ms
 I
ran model in 473.49 ms
sync in 213.30 ms
'
ran model in 213.23 ms
sync in 65.27 ms
m
ran model in 220.58 ms
sync in 61.86 ms
 a
ran model in 224.22 ms
sync in 63.64 ms
 
ran model in 200.98 ms
sync in 66.27 ms
2
ran model in 189.03 ms
sync in 66.51 ms
0
ran model in 192.33 ms
sync in 65.07 ms
 year
ran model in 230.38 ms
sync in 58.28 ms
 old
ran model in 225.56 ms
sync in 65.00 ms
```

**Comment by geohot** [comment]
Sweet! We're interested in readability > line count, but I do generally find shorter code easier to read.

**Comment by rayanht** [comment]
@geohot i’m down to the ~180ms on my M1 (running DEBUG=0, OPTLOCAL=1, and profiler disabled), curious to see if this latest rev makes a significant difference on your machine

**Comment by geohot** [comment]
```tiny@tiny:~/tinygrad$ python3 examples/llama.py --prompt "hello" --count 10 --timing
using GPU backend
loading 322 ram used: 13.48 GB: 100%|██████████████████████████████████████████████| 323/323 [00:02<00:00, 123.79it/s]
loaded weights in 2619.38 ms, 13.48 GB loaded at 5.15 GB/s
hello
/home/tiny/.local/lib/python3.10/site-packages/pyopencl/__init__.py:270: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
  warn("Non-empty compiler output encountered. Set the "
ran model in 440.73 ms
sync in 14.02 ms
,
ran model in 380.33 ms
sync in 8.02 ms
 and
ran model in 340.97 ms
sync in 7.85 ms
 welcome
ran model in 332.21 ms
sync in 7.69 ms
 to
ran model in 341.87 ms
sync in 6.68 ms
 the
ran model in 390.84 ms
sync in 6.97 ms
 one
ran model in 398.90 ms
sync in 6.39 ms
 and
ran model in 332.76 ms
sync in 7.54 ms
 only
ran model in 399.08 ms
sync in 7.59 ms
 web
ran model in 389.83 ms
sync in 7.77 ms```

A few notes. I'm indifferent to `OPTLOCAL` usage, 0 is none, 1 is every time, and 2 is hit the cache. It makes the GPU faster. Re: 100ms, best time is fine, so we're at 332.21 ms down from 450!

**Comment by geohot** [comment]
`python -O` is fine. 286.11 ms!

**Comment by geohot** [comment]
274.78 ms btw. In case my hotspots are different (EPYC 7662)

```
tiny@tiny:~/tinygrad$ python3 -c "import pstats; pstats.Stats('out.prof').sort_stats('tottime').print_stats(20)"
Tue May 30 01:16:25 2023    out.prof

         5948492 function calls (5547251 primitive calls) in 4.151 seconds

   Ordered by: internal time
   List reduced from 718 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
70280/58480    0.213    0.000    1.108    0.000 /home/tiny/tinygrad/tinygrad/lazy.py:171(movement_op)
42048/1816    0.156    0.000    1.409    0.001 /home/tiny/tinygrad/tinygrad/lazy.py:103(realize)
    59032    0.154    0.000    2.157    0.000 /home/tiny/tinygrad/tinygrad/tensor.py:21(apply)
    64616    0.134    0.000    0.450    0.000 /home/tiny/tinygrad/tinygrad/lazy.py:84(__init__)
    68712    0.114    0.000    0.838    0.000 /home/tiny/tinygrad/tinygrad/lazy.py:65(create_lazybuffer)
    62152    0.110    0.000    0.234    0.000 /home/tiny/tinygrad/tinygrad/tensor.py:39(__init__)
149352/102056    0.099    0.000    0.142    0.000 /home/tiny/tinygrad/tinygrad/ops.py:34(<listcomp>)
    90016    0.095    0.000    0.107    0.000 /usr/lib/python3.10/_weakrefset.py:86(add)
    64616    0.094    0.000    0.094    0.000 /usr/lib/python3.10/_weakrefset.py:37(__init__)
    59032    0.088    0.000    0.137    0.000 /home/tiny/tinygrad/tinygrad/tensor.py:13(__init__)
   100664    0.075    0.000    0.075    0.000 <string>:2(__init__)
149352/102056    0.063    0.000    0.187    0.000 /home/tiny/tinygrad/tinygrad/ops.py:34(get_buffers)
   127080    0.063    0.000    0.064    0.000 /home/tiny/tinygrad/tinygrad/shape/shapetracker.py:156(__init__)
    55440    0.063    0.000    0.066    0.000 /home/tiny/tinygrad/tinygrad/shape/shapetracker.py:48(__init__)
    12104    0.062    0.000    1.521    0.000 /home/tiny/tinygrad/tinygrad/tensor.py:455(_broadcasted)
    65592    0.058    0.000    0.130    0.000 /usr/lib/python3.10/weakref.py:153(__contains__)
    61496    0.054    0.000    0.124    0.000 /usr/lib/python3.10/weakref.py:165(__setitem__)
19040/15968    0.051    0.000    0.342    0.000 /home/tiny/tinygrad/tinygrad/lazy.py:244(_push_movement_ops)
15688/12616    0.046    0.000    0.607    0.000 /home/tiny/tinygrad/tinygrad/lazy.py:261(elementwise_op)
318569/220425    0.042    0.000    0.064    0.000 {built-in method builtins.len}
```

**Comment by geohot** [comment]
I'm also going to raise the bounty to $1,000 for a clean merge of the <100ms.

It looks like it'll require a bit more refactoring than I first thought.

**Comment by rayanht** [comment]
Haha trust me i've been staring at `movement_op` for a very very long time

Good to know you're fine with API being changed, i've been avoiding completely gutting the thing but yeah it's probably fine given that the only caller is `mlops.py`

Latest rev I managed to find an extra `10ms` down on my machine (130 -> 120), diminishing returns...

**Comment by rayanht** [comment]
Down another 10ms (~110ms/token) on my machine

We can probably get rid of a significant amount of overhead by having a dedicated method for each `MovementOps` in the `LazyBuffer` class instead of the generic `movement_op` but there would be a lot of repeated code, need to think about the refactor a bit more

**Comment by geohot** [comment]
248.80 ms on mine.

**Comment by geohot** [comment]
235.94 ms

**Comment by rayanht** [comment]
```
  def test_fold_conv_batchnorm_sgd(self):
    # TODO: with Tensor.training
    Tensor.training = True
    img = Tensor.ones(1,3,4,4)
    c1 = nn.Conv2d(3,32,3)
    bn = nn.BatchNorm2d(32, track_running_stats=False)
    opt = optim.SGD(optim.get_parameters([c1, bn]))
    with CLCache(allowed=18): # this is too high
      img_bn = bn(c1(img)).elu().sum()
      opt.zero_grad()
      img_bn.backward()
      opt.step()
    Tensor.training = False
```

Can now be tightened to 17, not quite sure what specific change caused this tbh

Referring to your comment on there though should we be able to do it with even less than 17? What's the lower bound?

**Comment by geohot** [comment]
Oh yea, it can be a lot lower. There's a $2,000 bounty for batchnorm fusion.

Run with GRAPH=1 to see the kernels.

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/codegen/linearizer.py            18              17
tinygrad/graph.py                          9               6
tinygrad/helpers.py                       15               8
tinygrad/lazy.py                         200             119
tinygrad/mlops.py                         37              19
tinygrad/nn/__init__.py                    1               1
tinygrad/nn/image.py                       2               1
tinygrad/ops.py                           51              25
tinygrad/runtime/lib.py                    2               1
tinygrad/runtime/ops_disk.py               1               1
tinygrad/runtime/ops_gpu.py                5               4
tinygrad/runtime/ops_metal.py              2               1
tinygrad/runtime/ops_torch.py              2               1
tinygrad/shape/shapetracker.py           117              78
tinygrad/shape/symbolic.py                19              19
tinygrad/tensor.py                        76              67
------------------------------------------------------------
total                                    557             368
------------------------------------------------------------
lines added in the tinygrad folder: 189
```

**Comment by rayanht** [comment]
Uhh so just noticed i'm using 3.11 which is probably part of the reason why my local benchmark is way faster than yours

On 3.10 I'm only getting 350ms/tok vs. 110ms/tok on 3.11

**Comment by geohot** [comment]
I'm fine with any Python version you want. I tried 3.11 and it wasn't faster, but I can try again

**Comment by rayanht** [comment]
The next most obvious thing I see is breaking the ref cycle of `LazyBuffer -> LazyOp.get_buffers().children -> LazyBuffer` so we don't have to pay the price of instantiating a WeakSet for each LB, need to think about it for a bit

**Comment by geohot** [comment]
Sorry, I broke LLaMA for non OS X. Should be fixed now, and a bit faster since the arange isn't copied in anymore.

**Comment by geohot** [comment]
Also, I think we do a slight relaxation to the target. The tinybox has a 2019 CPU, upstreamed 100ms on my M1 Max is fine too.

```
kafka@tubby:~/fun/tinygrad$ OPTLOCAL=2 DEBUG=0 python3.11 -O examples/llama.py --prompt "Hello." --count 10 --temperature 0 --timing
using METAL backend
loading 322 ram used: 13.48 GB: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 323/323 [00:03<00:00, 81.91it/s]
loaded weights in 3968.48 ms, 13.48 GB loaded at 3.40 GB/s
Hello.
ran model in 1044.90 ms
sync in 78.19 ms
 I
ran model in 139.72 ms
sync in 3.93 ms
'
ran model in 123.15 ms
sync in 4.30 ms
m
ran model in 116.01 ms
sync in 3.98 ms
 a
```

16% off

**Comment by rayanht** [comment]
Merging from master was a bit too messy with certain of my optimizations intertwined so I just took many changes from master as-is so I suspect this latest rev might be a bit slower than previous ones (although the arange + loadops refactor might offset that?).

Will do another pass at optimizing things from the merge

**Comment by rayanht** [comment]
Found a miraculous additional `10ms` down on my machine by getting rid of the stringification of the AST in the Linearizer for the method cache

```
(base) rayanht@MacBook-Pro tinygrad % DEBUG=0 OPTLOCAL=2 python3 -O examples/llama.py --prompt "Hello." --count 10 --temperature 0 --timing 
using GPU backend
ram used: 13.48 GB, freqs_cis                                         : 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 292/292 [00:23<00:00, 12.23it/s]
loaded weights in 23897.18 ms, 13.48 GB loaded at 0.56 GB/s
Hello.
ran model in 492.10 ms
sync in 4472.53 ms
 I
ran model in 108.11 ms
sync in 240.03 ms
'
ran model in 109.80 ms
sync in 135.65 ms
m
ran model in 129.88 ms
sync in 111.44 ms
 a
ran model in 105.79 ms
sync in 137.72 ms
 
ran model in 124.72 ms
sync in 116.38 ms
2
ran model in 99.76 ms
sync in 137.92 ms
0
ran model in 119.00 ms
sync in 124.34 ms
 year
ran model in 108.04 ms
sync in 126.74 ms
 old
ran model in 105.40 ms
sync in 124.18 ms
 male%                       
 ```

**Comment by geohot** [comment]
I ran ~10 times, I saw a 106.61 ms!

**Comment by rayanht** [comment]
Alright this latest rev might just about do it on your machine

**Comment by geohot** [comment]
Best is 105.86 ms

```
kafka@tubby:~/fun/tinygrad$ OPTLOCAL=2 DEBUG=0 python3.11 -O examples/llama.py --prompt "Hello." --count 10 --temperature 0 --timing
using METAL backend
ram used: 13.48 GB, freqs_cis                                         : 100%|███████████████████████████████████████████████| 292/292 [00:03<00:00, 93.03it/s]
loaded weights in 3145.90 ms, 13.48 GB loaded at 4.28 GB/s
Hello.
ran model in 802.71 ms
sync in 44.11 ms
 I
ran model in 134.01 ms
sync in 4.03 ms
'
ran model in 117.19 ms
sync in 3.83 ms
m
ran model in 105.86 ms
sync in 4.02 ms
 a
ran model in 116.10 ms
sync in 4.00 ms
 
ran model in 107.18 ms
sync in 4.01 ms
2
ran model in 116.07 ms
sync in 4.17 ms
0
ran model in 108.85 ms
sync in 4.01 ms
0
ran model in 108.43 ms
sync in 3.98 ms
0
ran model in 119.55 ms
sync in 3.73 ms
```

**Comment by rayanht** [comment]
Getting rid of FROMCPU made things a bit slower because of extra check but I think I managed to offset that, is the best still 105ms?

**Comment by geohot** [comment]
104.75

**Comment by rayanht** [comment]
There's something wrong with Metal btw, see the last few outputs of your previous run. Managed to repro on latest master as well.

Anyway this is where I'm at on GPU:

```
(base) rayanht@MacBook-Pro tinygrad % GPU=1 DEBUG=0 OPTLOCAL=2 python3 -O examples/llama.py --prompt "Hello." --count 10 --temperature 0 --timing 
using GPU backend
ram used: 13.48 GB, freqs_cis                                         : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 292/292 [00:20<00:00, 14.00it/s]
loaded weights in 20877.12 ms, 13.48 GB loaded at 0.65 GB/s
Hello.
ran model in 520.36 ms
sync in 4050.95 ms
 I
ran model in 159.61 ms
sync in 270.87 ms
'
ran model in 117.42 ms
sync in 132.82 ms
m
ran model in 100.74 ms
sync in 139.41 ms
 a
ran model in 104.86 ms
sync in 126.98 ms
 
ran model in 99.30 ms
sync in 144.31 ms
2
ran model in 98.71 ms
sync in 145.64 ms
0
ran model in 105.88 ms
sync in 129.67 ms
 year
ran model in 101.19 ms
sync in 143.48 ms
 old
ran model in 102.03 ms
sync in 127.31 ms
 male% 
 ```

**Comment by roelofvandijk** [comment]
I have some ideas for you @rayanht, I hope it is OK if I chime in here.

## Node types

Instead of `x.__class__ == int` you could use `int(x) == x`. It is probably faster, but less safe (e.g. [will accept 5.0](https://stackoverflow.com/a/48940855/12149698)). 

Instead of using `x.__class__` for all the node type checks, you could define a node type property (integer, "node_type") and set it at initialization, then check against it. 

```
NUMNODE =  1
[...]
def __init__(self):
  self.node_type = NUMNODE
[...]
if this.node_type == NUMNODE:
```

## Generating constant lists/tuples

There are quite some locations where constant lists/tuples are generated using `for _ in abc`.
It's much faster to multiply:
old:
```
axis_groups: List[List[int]] = [[] for _ in range(len(new_shape))]
```
new:
```
axis_groups: List[List[int]] = [[],] * len(new_shape)
```

It might make sense to check all uses of `for _ in`.

## Checks for None
There are some locations that check if a list contains `None` by using `if any([v is None for v in abc])`. It's faster to use `if None in abc`.

See the `requires_grad` in the init of `BinaryFunction` in `tensor.py`, which becomes faster using:
```
self.requires_grad = True if True in self.needs_input_grad else None if None in self.needs_input_grad else False
```
instead of 
``` 
self.requires_grad = True if any(self.needs_input_grad) else (None if any([x is None for x in self.needs_input_grad]) else False)
```

## enumerate

There are some locations looping over `len(range(abc))`, many changed to use enumerate. In some places, the decision seems conscious to keep the code easy to read (e.g. in `linearizer.py`). It might make sense to check all uses of `range(len(` in the codebase.

In some other places you can directly iterate over the container, e.g.:
`narg = tuple([self.op.arg[arg[i]] for i in range(len(arg))])` -> `narg = tuple([self.op.arg[a] for a in arg])`


## DType

In the tensor init you could use `assert dtype is None or dtype in DTYPES_DICT, f"invalid dtype {dtype}"`


## Miscellaneous

In some places you check if the len of a list is zero (e.g. `if len(self.children) == 0`), I think it is faster to just use `if not self.children`

I'll add more things here if I find them. Let me know if you'd like me to comment in the code directly.

**Comment by geohot** [comment]
I really wanted to see it be under 100ms, so I niced -20 the process and disabled the GC.
```
kafka@tubby:~/fun/tinygrad$ METAL=1 python3.11 -O examples/llama.py --prompt "Hello." --count 20 --temperature 0 --timing
using METAL backend
ram used: 13.48 GB, freqs_cis                                         : 100%|███████████████████████████████████████████████| 292/292 [00:03<00:00, 73.09it/s]
loaded weights in 4003.05 ms, 13.48 GB loaded at 3.37 GB/s
...
ran model in 99.08 ms
sync in 3.89 ms
 a
ran model in 98.37 ms
sync in 4.14 ms
 student
ran model in 97.11 ms
sync in 3.88 ms
 at
```

**Comment by geohot** [comment]
Re the `from math import prod` everywhere, wouldn't it be the same speed to just import that function in helpers? (idk why I wrapped it and didn't just do that) I like it being in helpers since I already import that everywhere.

**Comment by rayanht** [comment]
the function call overhead in python is kinda ridiculous

prod is called super often so by avoiding one level of call frame depth you actually save a non-trivial amount of time

let me re-run some benchmarks of the two options just to validate that that specific change is actually worth it

**Comment by geohot** [comment]
Oh yea, you can avoid the overhead without changing all the files.

In tinygrad/helpers.py:
`from math import prod`

In others:
`from tinygrad.helpers import prod`

**Comment by rayanht** [comment]
oh yeah

sounds good, i'll break this up into more manageable PR and submit them

**Comment by geohot** [comment]
Is there more to still be merged?

**Comment by rayanht** [comment]
I think that's it

We diverge in perf because this branch has all the stuff with UnaryFunction/BinaryFunction that you weren't fond of

**Comment by geohot** [comment]
Yea, I looked at the profiler and saw why you wanted that. If there's a way to do it while reducing lines/complexity I'm open to it, but not trading that off.

It turns out if you disable the LAZYCACHE it's under 100ms (in master). Bounty is yours, george@tinygrad.org to claim or post a PayPal e-mail. Congrats on the first $1000 bounty!

```
kafka@tubby:~/fun/tinygrad$ LAZYCACHE=0 python3.11 -O examples/llama.py --prompt "Hello." --count 10 --temperature 0 --timing
using METAL backend
ram used: 13.48 GB, freqs_cis                                         : 100%|█████████████████████████████████████████████████████████████| 292/292 [00:03<00:00, 93.37it/s]
loaded weights in 3133.60 ms, 13.48 GB loaded at 4.30 GB/s
Hello.
ran model in 1438.79 ms
sync in 46.59 ms
 I
ran model in 129.88 ms
sync in 3.66 ms
'
ran model in 97.05 ms
sync in 3.72 ms
m
```

**Pull request closed without merging**
