### PR TITLE
Apple llvm version vectorization

### PR DESCRIPTION
**Pull request by calledit**
Does not vectorize with normal llvm, but will vectorize on apple llvm.

### CODE REVIEW

**Comment by calledit** [comment]
To get this vectorization working we need to change the loop structure in tinygrad.
If we look at this c-code we see that it vectorizes fine by looking at LLVM output, the thing that is different that I can think of is that the Phi instructions is outside of the loop.

clang -S -emit-llvm  -O0 vectorize.c

```
#include <stdlib.h>
int add_float_good(float *restrict ap)
{
    float ma = -4;
    for(size_t i=0;i<64;++i) {
       if(ap[i]>ma){
           ma = ap[i];
       }
    }
	return(int) ma;
}


int main() {
 float array[] = {3.544, 5.544, 6.544, 6.544};
return add_float_good(array);
}
```

This is the vectorized llvm
```
@__const.main.array = private unnamed_addr constant [4 x float] [float 0x400C5A1CA0000000, float 0x40162D0E60000000, float 0x401A2D0E60000000, float 0x401A2D0E60000000], align 16
; Function Attrs: norecurse nounwind readonly ssp uwtable
define i32 @add_float_good(float* noalias nocapture readonly %0) local_unnamed_addr #0 {
  br label %4

2:                                                ; preds = %4
  %3 = fptosi float %25 to i32
  ret i32 %3

4:                                                ; preds = %4, %1
  %5 = phi i64 [ 0, %1 ], [ %26, %4 ]
  %6 = phi float [ -4.000000e+00, %1 ], [ %25, %4 ]
  %7 = getelementptr inbounds float, float* %0, i64 %5
  %8 = load float, float* %7, align 4, !tbaa !4
  %9 = fcmp ogt float %8, %6
  %10 = select i1 %9, float %8, float %6
  %11 = or i64 %5, 1
  %12 = getelementptr inbounds float, float* %0, i64 %11
  %13 = load float, float* %12, align 4, !tbaa !4
  %14 = fcmp ogt float %13, %10
  %15 = select i1 %14, float %13, float %10
  %16 = or i64 %5, 2
  %17 = getelementptr inbounds float, float* %0, i64 %16
  %18 = load float, float* %17, align 4, !tbaa !4
  %19 = fcmp ogt float %18, %15
  %20 = select i1 %19, float %18, float %15
  %21 = or i64 %5, 3
  %22 = getelementptr inbounds float, float* %0, i64 %21
  %23 = load float, float* %22, align 4, !tbaa !4
  %24 = fcmp ogt float %23, %20
  %25 = select i1 %24, float %23, float %20
  %26 = add nuw nsw i64 %5, 4
  %27 = icmp eq i64 %26, 64
  br i1 %27, label %2, label %4
}
; Function Attrs: nounwind readnone ssp uwtable
define i32 @main() local_unnamed_addr #1 {
  br label %1

1:                                                ; preds = %1, %0
  %2 = phi i64 [ 0, %0 ], [ %23, %1 ]
  %3 = phi float [ -4.000000e+00, %0 ], [ %22, %1 ]
  %4 = getelementptr inbounds [4 x float], [4 x float]* @__const.main.array, i64 0, i64 %2
  %5 = load float, float* %4, align 16, !tbaa !4, !alias.scope !8
  %6 = fcmp ogt float %5, %3
  %7 = select i1 %6, float %5, float %3
  %8 = or i64 %2, 1
  %9 = getelementptr inbounds [4 x float], [4 x float]* @__const.main.array, i64 0, i64 %8
  %10 = load float, float* %9, align 4, !tbaa !4, !alias.scope !8
  %11 = fcmp ogt float %10, %7
  %12 = select i1 %11, float %10, float %7
  %13 = or i64 %2, 2
  %14 = getelementptr inbounds [4 x float], [4 x float]* @__const.main.array, i64 0, i64 %13
  %15 = load float, float* %14, align 8, !tbaa !4, !alias.scope !8
  %16 = fcmp ogt float %15, %12
  %17 = select i1 %16, float %15, float %12
  %18 = or i64 %2, 3
  %19 = getelementptr inbounds [4 x float], [4 x float]* @__const.main.array, i64 0, i64 %18
  %20 = load float, float* %19, align 4, !tbaa !4, !alias.scope !8
  %21 = fcmp ogt float %20, %17
  %22 = select i1 %21, float %20, float %17
  %23 = add nuw nsw i64 %2, 4
  %24 = icmp eq i64 %23, 64
  br i1 %24, label %25, label %1

25:                                               ; preds = %1
  %26 = fptosi float %22 to i32
  ret i32 %26
}
```

Unvectorized version:
```
@__const.main.array = private unnamed_addr constant [4 x float] [float 0x400C5A1CA0000000, float 0x40162D0E60000000, float 0x401A2D0E60000000, float 0x401A2D0E60000000], align 16
; Function Attrs: noinline nounwind optnone ssp uwtable
define i32 @add_float_good(float* noalias %0) #0 {
  %2 = alloca float*, align 8
  %3 = alloca float, align 4
  %4 = alloca i64, align 8
  store float* %0, float** %2, align 8
  store float -4.000000e+00, float* %3, align 4
  store i64 0, i64* %4, align 8
  br label %5

5:                                                ; preds = %21, %1
  %6 = load i64, i64* %4, align 8
  %7 = icmp ult i64 %6, 64
  br i1 %7, label %8, label %24

8:                                                ; preds = %5
  %9 = load float*, float** %2, align 8
  %10 = load i64, i64* %4, align 8
  %11 = getelementptr inbounds float, float* %9, i64 %10
  %12 = load float, float* %11, align 4
  %13 = load float, float* %3, align 4
  %14 = fcmp ogt float %12, %13
  br i1 %14, label %15, label %20

15:                                               ; preds = %8
  %16 = load float*, float** %2, align 8
  %17 = load i64, i64* %4, align 8
  %18 = getelementptr inbounds float, float* %16, i64 %17
  %19 = load float, float* %18, align 4
  store float %19, float* %3, align 4
  br label %20

20:                                               ; preds = %15, %8
  br label %21

21:                                               ; preds = %20
  %22 = load i64, i64* %4, align 8
  %23 = add i64 %22, 1
  store i64 %23, i64* %4, align 8
  br label %5

24:                                               ; preds = %5
  %25 = load float, float* %3, align 4
  %26 = fptosi float %25 to i32
  ret i32 %26
}
; Function Attrs: noinline nounwind optnone ssp uwtable
define i32 @main() #0 {
  %1 = alloca i32, align 4
  %2 = alloca [4 x float], align 16
  store i32 0, i32* %1, align 4
  %3 = bitcast [4 x float]* %2 to i8*
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 16 %3, i8* align 16 bitcast ([4 x float]* @__const.main.array to i8*), i64 16, i1 false)
  %4 = getelementptr inbounds [4 x float], [4 x float]* %2, i64 0, i64 0
  %5 = call i32 @add_float_good(float* %4)
  ret i32 %5
}
```

**Comment by geohot** [comment]
Doesn't work for me. Run the test like this, max should be similar speed to sum when vectorized.

```
kafka@tubby:~/fun/tinygrad$ OPT=2 LLVM=1 python3 test/test_speed_v_torch.py TestSpeed.test_sum TestSpeed.test_max
sum                            4096x4096    1.26 ms in torch,    1.34 ms in tinygrad,    1.06x slower 1057.2368 1057.2544
.max                            4096x4096    1.43 ms in torch,   11.20 ms in tinygrad,    7.82x slower 0.49999988 0.49999988
.
----------------------------------------------------------------------
Ran 2 tests in 0.452s

OK
```

**Comment by calledit** [comment]
> Doesn't work for me. Run the test like this, max should be similar speed to sum when vectorized.
Yeah, we are not using apple llvm.

My understanding after downloading llvm v11 (which is the version of llvm that llvmlite uses) and looking at its source, is that we need to generate IR where the Phi instruction is inside the same basic_block as the instruction that is computing on the variable.(in this case the select and compare instructions).

Currently tinygrad generates this IR:
```
define void @"exec"(float* %".1", float* %".2")
{
entry:
  br label %"loop_0"
loop_0:
  %"idx_0_0" = phi  i64 [0, %"entry"], [%".4", %"loopexit_0"]
  %"idx_1_0" = phi  i64 [0, %"entry"], [%".5", %"loopexit_0"]
  %"reduce_phi_1" = phi  float [0xfff0000000000000, %"entry"], [%".9", %"loopexit_0"]
  %"loopvar_0" = phi  i64 [0, %"entry"], [%".13", %"loopexit_0"]
  br label %"loopexit_0"
loopexit_0:
  %".4" = add i64 %"idx_0_0", 1
  %".5" = add i64 %"idx_1_0", 1
  %".6" = getelementptr inbounds float, float* %".2", i64 %"idx_1_0"
  %".7" = load float, float* %".6"
  %".8" = fcmp fast ult float %"reduce_phi_1", %".7"
  %".9" = select fast i1 %".8", float %".7", float %"reduce_phi_1"
  %".13" = add i64 %"loopvar_0", 1
  %".14" = icmp eq i64 %".13", 16777216
  br i1 %".14", label %"exit", label %"loop_0"
exit:
  %".10" = getelementptr inbounds float, float* %".1", i64 0
  store float %".9", float* %".10"
  ret void
}
```

But it would need to generate something like this:
```
define void @"exec"(float* %".1", float* %".2")
{
entry:
  br label %"loop_0"
loop_0:
  %"idx_0_0" = phi  i64 [0, %"entry"], [%".4", %"loop_0"]
  %"idx_1_0" = phi  i64 [0, %"entry"], [%".5", %"loop_0"]
  %"reduce_phi_1" = phi  float [0xfff0000000000000, %"entry"], [%".9", %"loop_0"]
  %"loopvar_0" = phi  i64 [0, %"entry"], [%".13", %"loop_0"]
  %".4" = add i64 %"idx_0_0", 1
  %".5" = add i64 %"idx_1_0", 1
  %".6" = getelementptr inbounds float, float* %".2", i64 %"idx_1_0"
  %".7" = load float, float* %".6"
  %".8" = fcmp fast ult float %"reduce_phi_1", %".7"
  %".9" = select fast i1 %".8", float %".7", float %"reduce_phi_1"
  %".13" = add i64 %"loopvar_0", 1
  %".14" = icmp eq i64 %".13", 16777216
  br i1 %".14", label %"exit", label %"loop_0"
exit:
  %".10" = getelementptr inbounds float, float* %".1", i64 0
  store float %".9", float* %".10"
  ret void
}
```


I have tried to force tinygrad to to it, but it is over my head.

**Comment by calledit** [comment]
No, I take all that back.

**Comment by calledit** [comment]
Here we go again(using this page as a scratchpad):
Stepping through the output and correlating to the llvm source
in llvm 11
Transforms/Vectorize/LoopVectorizationLegality.cpp

First the debug output in tinygrad says "Found an induction variable" this means it has come to the function 
Transforms/Vectorize/LoopVectorizationLegality.cpp -> LoopVectorizationLegality::addInductionPhi
This means the optimiser found returned true in Transforms/Vectorize/LoopVectorizationLegality.cpp -> InductionDescriptor::isInductionPHI either line 554, 664 or 680
Then the debug output says "Found an unidentified PHI   %reduce_phi_1 = phi float [ 0.000000e+00, %entry ], [ %.8, %loop_0 ]" Transforms/Vectorize/LoopVectorizationLegality.cpp line 684

We are garantied to run in to InductionDescriptor::isInductionPHI that function will then call to InductionDescriptor::isFPInductionPHI()
which contains this
```
if (BOp->getOpcode() == Instruction::FAdd) {
    if (BOp->getOperand(0) == Phi)
      Addend = BOp->getOperand(1);
    else if (BOp->getOperand(1) == Phi)
      Addend = BOp->getOperand(0);
  } else if (BOp->getOpcode() == Instruction::FSub)
    if (BOp->getOperand(0) == Phi)
      Addend = BOp->getOperand(1);
```
This is why the fadd will optimize.

There is another path to optimization the function RecurrenceDescriptor::isFirstOrderRecurrence()
It first checks that the loop has a preheader.  It think we have that.
But then we come to this
//If the user of the PHI is also the incoming value, we potentially have a reduction and which cannot be handled by sinking
And the isFirstOrderRecurrence() return false since tinygrad is using the value it is itself generating.
So we can to get to vectorization through RecurrenceDescriptor::isFirstOrderRecurrence()

Another path to vectorization is RecurrenceDescriptor::isReductionPHI()

RecurrenceDescriptor::isReductionPHI() literally mention MinMax and the name of the function sounds good.
Seams like we just need to set HasFunNoNaNAttr I have seen people mention that on google to.. but how...

By adding func.attributes.add('"no-nans-fp-math"="true"') and altering /usr/local/lib/python3.9/site-packages/llvmlite/ir/values.py so that it is allowed....
Does not work anyway....



Aha due to the fact that llvmlite does not setup its TargetOptions from the function
InitTargetOptionsFromCodeGenFlags()
All our settings are being ignored.

We want to set Options.NoNaNsFPMath but that is literally not possible in llvmlite.

Dejavuu... Feels like I have been here before....

And it should be enogh to set "no-nans-fp-math"="true" on a function level...

Enough for this session. This shit is to addictive....

**Pull request closed without merging**
