### PR TITLE
simplify deepwalk

### PR DESCRIPTION
**Pull request by daulet**
Model can't have cycles so we don't need track visited nodes. Also win more lines

### CODE REVIEW

**Comment by geohot** [comment]
I don't think this works. While it can't have cycles, it can have diamonds.

A
|
|----
v.     v
B     C
|.      |
-----
   v
  D

**Comment by kartik4949** [comment]
agreed with @geohot, i had similar problem in my framework too :)
try with
x = a + b
y = x * a
y.backward()

**Comment by geohot** [comment]
Let's add that as a test

**Comment by daulet** [comment]
Yes, this would return duplicates nodes on such models (didn't know they exist), although still terminates. I've created a suggested test, however can't make it fail with this change. I suspect backward() logic is somehow resilient to duplicates. Investigating.

Once I have the test I'll abandon this PR since all useful stuff is already integrated.

**Comment by adamritter** [comment]
The leaf nodes aren't visited, that may be the reason

**Pull request closed without merging**
