### PR TITLE
:zap: Added softplus and mish non stable

### PR DESCRIPTION
**Pull request by kartik4949**
mish (non first class) and softplus (first class) implementation.
if anyone can try to make softplus as second class please let me know.
#216

### CODE REVIEW

**Comment by geohot** [comment]
Yea I'd much rather it be second class. I'm thinking about adding Log and Exp as first class and removing LogSoftmax

**Comment by geohot** [comment]
Check out the refactor. Log and Exp are first class.

**Comment by kartik4949** [comment]
Let me look into it

**Comment by kartik4949** [comment]
done note 
current implementation is not stable as it doesnt limit input
i.e 
https://pytorch.org/docs/stable/generated/torch.nn.Softplus.html
refer this @geohot

**Comment by kartik4949** [comment]
if Input×β > threshold i.e 20 default it makes the softplus as linear without changing the input 
im thinking how to implement this functionality in tinygrad.

**Comment by GeorgeDeac** [comment]
This should be as easy as: `return self * beta > limit ? self : (1/beta)*ret  // In softplus definition`
And in the backward we must also cap it in regards to the input data again.

**Comment by kartik4949** [comment]
Self*beta > limit wont work unless '__lt__' is not implemented

**Comment by GeorgeDeac** [comment]
Oh right, didn't know rich comparisons weren't yet implement

**Comment by kartik4949** [comment]
Maybe we can limit the input*beta later. and move with this :)

**Comment by geohot** [comment]
Fix conflicts, and I'll merge if tests pass.

**Comment by kartik4949** [comment]
Ok

**Comment by kartik4949** [comment]
ready for merge.

**Pull request merged**
