### PR TITLE
Remove examples/deep_deterministic_policy_gradient.py

### PR DESCRIPTION
**Pull request by jla524**

### CODE REVIEW

**Comment by dc-dc-dc** [comment]
Closes: #659

**Comment by geohot** [comment]
Hmm, actually why was that error happening?

**Comment by geohot** [comment]
Hmm, actually why was that error happening? This code is pretty clean, why doesn't it work? Why is it slow?

**Comment by jla524** [comment]
if I’m not mistaken, this is training on a batch size of 1, and tinygrad is kinda slow vs PyTorch when batch size is 1

**Pull request closed without merging**
