### PR TITLE
add ptx formatter + syntax highlighter

### PR DESCRIPTION
**Pull request by cloud11665**
Also doing formatting as it's easier to compare ptx to cuda backend code.
orange - instruction or immediate value
purple - state space
blue - operand or identifier
green - type
white - modifier (be it infix or prefix)
image

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/runtime/ops_cuda.py              19               2
------------------------------------------------------------
lines added in the tinygrad folder: 17
```

**Comment by geohot** [comment]
It's not obvious to me reading this that the text will always be the same (just colored differently)

**Comment by cloud11665** [comment]
oh, so we don't want to format it (fix indentation on args and instructions, add newlines for params) ?

**Comment by geohot** [comment]
I'd merge the colorizer.

**Comment by cloud11665** [comment]
> I'd merge the colorizer (if it's clear from code it's just a colorizer), I think the formatting is fine from what I've seen. The risk is that it misprints the ptx and that bug wastes hours of someone's time.

Done. Explained in the comment in code:
 all expressions match `<valid_before><expr><valid_after>` and replace it with `<valid_before>color(<expr>)<valid_after>`
 
 The only caveat is that we don't color conditional instructions, but doing that would add additional complexity to the tokenizer which I don't think is worth it.

**Comment by geohot** [comment]
Thanks!

**Pull request merged**
