### PR TITLE
Fix MovementOps.EXPAND print issue for DEBUG=3

### PR DESCRIPTION
**Pull request by kw3rk**
Add space rather than empty string to prevent print from assuming we don't want a newline at the end of text

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/ops.py                            1               1
------------------------------------------------------------
lines added in the tinygrad folder: 0
```

**Comment by geohot** [comment]
I don't follow this, this changes the behavior of print? Can you post a before and after?

**Comment by kw3rk** [comment]
Tested in my Ubuntu rig and the issue didn't show up. This looks like an issue in Windows WSL where I was working earlier today. Maybe the WSL shell handles certain newline characters differently? I can post screenshots tomorrow morning when I'm back in the environment I was using. The MovementOps.EXPAND lines had the next line tacked on at the end.

**Comment by geohot** [comment]
Going to close for now, if you can repro reopen

**Comment by kw3rk** [comment]
Deleting branch. After pulling a clean clone and trying to recreate for screenshots, I was unable to replicate the issue. I have no idea what was originally causing it, but since it can't be reproduced it's not an issue. Going back under my rock now.

**Pull request closed without merging**
