### PR TITLE
Somewhat more generic broadcasting

### PR DESCRIPTION
**Pull request by adamritter**

### CODE REVIEW

**Comment by adamritter** [comment]
I see that there's a competing pull request, this broadcasting works for all easy cases that don't need changing of the current binary_op kernel (and in return it doesn't slow binary_op kernel down). test_ops.py passes on my computer.

**Comment by geohot** [comment]
The other PR doesn’t work. Why do the tests fail on this one?

**Comment by adamritter** [comment]
I guess it doesn't have random seed set, and there's no flakyness check in
the testing pipeline. I haven't touched the conv code as you can see.

**Comment by adamritter** [comment]
I mean some random seed is not initialized inside the test probably.

**Comment by ryanneph** [comment]
I haven’t taken a close look at either implementation yet, but more test cases need to be added before any broadcasting patch can be confidently merged, IMO. There’s only one right now and it has two unique integers (32, 1) across four dimensions. There’s a possibility for incomplete broadcasting implementations to pass since there’s ambiguity in the shape ordering.

**Comment by adamritter** [comment]
Sure, I agree that more unit tests are needed. I just tried some deep cases
(shapes of 6 dimensions) by hand to see that broadcasting mostly works, and
tried to keep the implementation easy to understand while being concise at
the same time.

**Comment by ryanneph** [comment]
Got it. I didn’t know that you had tested more locally. Nice job

**Comment by ryanneph** [comment]
Btw, did you/do you have a chance to test against train_efficientnet (#104), which relies on working broadcasting?

**Comment by adamritter** [comment]
I'm quite sleepy right now, but this implementation works only for 1s on
the right.

Actually 1s on the left could be added as another special case that doesn't
complicate the kernel.

**Comment by adamritter** [comment]
That's the mod that the issue was about...it wouldn't be that hard to
extend the current code.

**Comment by adamritter** [comment]
Calling the subfunction with reverses of the shapes would be an option.

**Comment by geohot** [comment]
yea, needs mod. And we should write more tests

**Pull request merged**
