### PR TITLE
Pad2d backward pass on GPU

### PR DESCRIPTION
**Pull request by adamritter**

### CODE REVIEW

**Comment by geohot** [comment]
Can you enable the test?

**Comment by adamritter** [comment]
> Can you enable the test?

Sure, but I just realized that the       for (int x = 0; x < ix; x++) will be out of bounds... I really wanted to not blow up the code base, but it seems like it's better if I create a new kernel

**Comment by adamritter** [comment]
Actually the GPU test was already enabled and passing, so I'm not sure what do you mean by enabling the test

**Comment by adamritter** [comment]
Can you take another look?

The GPU test was failing before I checked out the code, and it's passing now on my computer.

**Comment by geohot** [comment]
Hmm, I think I just disabled it. Will merge and fix.

**Comment by geohot** [comment]
https://github.com/geohot/tinygrad/commit/870b84a89370118d34c3dcc159d59b831df7bee9

**Comment by geohot** [comment]
If you get a chance, can you refactor this to reuse the kernel from the forward pass?

**Comment by adamritter** [comment]
Sure

**Pull request merged**
