### PR TITLE
Add BCELoss and BCELossWithLogits to training.py

### PR DESCRIPTION
**Pull request by MahirAbbas**
initial implementation. two implementations of BCELoss, one which adds epsilon small (same way in pytorch) and one with clamping.
also BCELossWithLogits. no clamping/EPS as sigmoid should remove issue of 0 in 99% scenarios. can add.

### CODE REVIEW

**Comment by MahirAbbas** [comment]
pytorch does use EPS, and not clamping. probably more performant

**Comment by geohot** [comment]
Tests failing. Also, this introduces new functionality. Whenever new functionality is introduced it needs to be tested.

**Comment by MahirAbbas** [comment]
put test file in /test (don't know if correct place). BCEWithLogitsLoss outputs different values  than in pytorch. definitions seem to be the same. created two models in /test/test_BCELoss. one in pytorch and one in tinygrad. manually set weights. loss is different from pytorch

**Comment by MahirAbbas** [comment]
need to add more test. initial test works now.

**Comment by geohot** [comment]
Tests not in a framework, EPS isn't a param, not used anywhere. For now, won't merge.

**Pull request closed without merging**
