### PR TITLE
Refactor nn.optim

### PR DESCRIPTION
**Pull request by rezaarezvan**
Just a nice one-liner using list comprehension. Also fixes all tests that previously imported `get_parameters` from `tinygrad.nn.optim` or similar - removing that useless import at the end of `optim.py`.

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/nn/optim.py                       2               6
------------------------------------------------------------
lines added in the tinygrad folder: -4
```

**Comment by geohot** [comment]
Very incomplete. `get_parameters` is used in optim in many more places.

Also, I don't generally like the list comprehensions that are only for side effects.

**Comment by rezaarezvan** [comment]
> Very incomplete. `get_parameters` is used in optim in many more places.
> 
> Also, I don't generally like the list comprehensions that are only for side effects.

Alright I'll find and replace the rest of `get_parameters` usage in optim. I'll also drop the list comprehension I guess

**Comment by rezaarezvan** [comment]
I think I've replaced all instances of `optim.get_parameters` and `optim.get_state_dict` now.

**Comment by wozeparrot** [comment]
Missing the change in `docs/quickstart.md`

**Comment by rezaarezvan** [comment]
> Missing the change in `docs/quickstart.md`

Oh yeah - missed the docs :P

**Pull request merged**
