### PR TITLE
Implemented AdaBelief optimizer

### PR DESCRIPTION
**Pull request by ziofil**
Implemented [AdaBelief optimizer](https://juntang-zhuang.github.io/adabelief/) as the option `Adam(AdaBelief=True)`.

I couldn't write a test because AdaBelief is not part of torch by default. There are [packages](https://pypi.org/project/adabelief-pytorch/) though, so perhaps there's a way to include them in the version of torch that is used for tests.

### CODE REVIEW

**Comment by geohot** [comment]
Remove vscode settings, and hopefully tests will pass.

**Comment by geohot** [comment]
Though actually, I really like this one. It's running on the main comma model now, we'll see how it does :)

**Comment by ziofil** [comment]
I removed `.vscode/` but the tests still fail because the gzip file of the MNIST data fails to download from Yann LeCun's website 😅

**Comment by UmarJ** [comment]
Commit 81bf933a9198b5175517900ee8f1dff3b4ad96d2 fixes the tests failing because of LeCun's site being down, but the tests on this PR [still fail](https://github.com/UmarJ/tinygrad/actions/runs/937752126) because you're not saving the `AdaBelief` kwarg when initializing `Adam`.

I fixed this and the tests [pass now](https://github.com/UmarJ/tinygrad/actions/runs/937755715). Opened https://github.com/ziofil/tinygrad/pull/1, merging which into your fork will update this PR as well.

Maybe a test for AdaBelief should be added as well?

**Comment by geohot** [comment]
Not as good as ADAM.

Since there's no consensus it's better, I'm not going to merge this.

**Pull request closed without merging**
