### PR TITLE
safetensors!

### PR DESCRIPTION
**Pull request by geohot**

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/runtime/ops_disk.py              10               6
------------------------------------------------------------
lines added in the tinygrad folder: 4
```

**Comment by wozeparrot** [comment]
Played around with this for a bit here: https://github.com/wozeparrot/tinygrad/tree/bert_safetensors
```py
from models.bert import BertForPreTraining
from tinygrad import state
from extra.utils import get_child

# convert to safetensors
mdl = BertForPreTraining()
mdl.load_from_pretrained()
state.safe_save(state.get_state_dict(mdl), "/tmp/bert_for_pt.safetensors")

del mdl

# try to load safetensors
mdl = BertForPreTraining()
state_dict = state.safe_load("/tmp/bert_for_pt.safetensors")
for k, v in state_dict.items():
  get_child(mdl, k).assign(v.numpy()).realize()
```

Seems to work.

Should probably also move `get_child` to state as well tho, because it is needed to load from the state_dict.

**Comment by geohot** [comment]
I don't like get_child. Try `get_state_dict` on mdl and assigning to those tensors.

**Comment by wozeparrot** [comment]
Ok, yea that seems to work

**Pull request merged**
