### PR TITLE
Added CUDA support through cupy

### PR DESCRIPTION
**Pull request by elb3k**
Used [cupy](https://cupy.dev/) for GPU-accelerated numpy operations.
Almost one to one correspondence with numpy, copied `ops_cpu.py` to `ops_gpu.py` with `cupy` instead of `numpy`.

Speed improvements compared to OpenCL are substantial, `test_net_speed.py` in GTX 1080 Ti:
Cupy:
```
forward pass:  7.190 ms, 0.01x off baseline 1222.719 ms
backward pass: 105.258 ms, 0.02x off baseline 4840.096 ms
```
vs OpenCL:
```
forward pass:  35.964 ms, 0.02x off baseline 1888.007 ms
backward pass: 1174.037 ms, 0.18x off baseline 6650.118 ms
```

### CODE REVIEW

**Comment by geohot** [comment]
What about non Nvidia GPUs? This would have to be added as a different arch

**Comment by elb3k** [comment]
> What about non Nvidia GPUs? This would have to be added as a different arch

Separated cuda as new ops, can be installed in `tinygrad[cuda]`.

**Comment by geohot** [comment]
Hmm, I mean it should be supported like ops_cuda, it shouldn't require a separate install.

**Comment by elb3k** [comment]
> Hmm, I mean it should be supported like ops_cuda, it shouldn't require a separate install.

It is supported as ops_cuda, But I added `cupy` dependency like `pyopencl` in setup.py
```python
 extras_require={
        'gpu': ["pyopencl", "six"],
        'cuda': ["cupy", "six"]
```

**Comment by geohot** [comment]
So is this just a copy of ops_cpu? Is there a clever way to do this with less lines?

**Comment by geohot** [comment]
I'd merge something like this, but with much less lines! Check out what I did for TORCH

**Pull request closed without merging**
