### PR TITLE
n step optim + sgd w/ momentum

### PR DESCRIPTION
**Pull request by JJJJJJJJJJJJJJJl**
Actually getting weird behaviour. For values of 10, 20, 50 for the number of steps, either all four tests fail or pass (in a 10:1 scale). But in 100 steps, either Adam passes and the rest fail or all fail (also ~90% all four failing).

Testing on a M1 if it matters.

### CODE REVIEW

**Comment by geohot** [comment]
Any luck figuring out why it's failing?

**Comment by JJJJJJJJJJJJJJJl** [comment]
Haven't figured the root cause, but found something particularly interesting. If you access out's data within the training loop, as such..

```
def walk_tinygrad(optim, steps, kwargs={}):
  net = TinyNet()
  optim = optim([net.x, net.W], **kwargs)
  for _ in range(steps):
    out = net.forward()
    out.data
    out.backward()
    optim.step()
  return net.x.cpu().data, net.W.cpu().data
```

then SGD (without momentum) seems to work just fine. This goes slightly beyond me honestly as I don't have a complete understanding over the project's workings, but I sense there's something (very) broken internally. I fear these one apparently neutral lines fixes

It would be great if you can confirm this behaviour so I can discard the doubts regarding my setup lol

**Comment by geohot** [comment]
Hmm, try "out.realize()" instead of "out.data" and see if that fixes it.

**Comment by geohot** [comment]
Please reopen if you fix it

**Pull request closed without merging**
