### PR TITLE
Count Python tokens

### LINKED ISSUE #743: Use tokens as the 'tiny' metric instead of lines
The current state of things is goofy. Your lines are long as heck because you promised to keep things under 1000 lines. That's obviously cheating, and SLoC is a bad metric anyway. Better to set an upper bound on the number of tokens, as counted by Python's `tokenize`.

If you want to put an upper bound on code complexity, use units which can't be "stuffed" with extra complexity.

### PR DESCRIPTION
**Pull request by khazit**
Closes #743 

Token types are defined here : https://docs.python.org/3/library/token.html
To avoid inflating the token count with line breaks, comments, indents, only 4 types of tokens are counted : 
```python
TOKEN_WHITELIST = [
    token.OP,
    token.NAME,
    token.NUMBER,
    token.STRING
]
```
About `token.OP`:
> To simplify token stream handling, all [operator](https://docs.python.org/3/reference/lexical_analysis.html#operators) and [delimiter](https://docs.python.org/3/reference/lexical_analysis.html#delimiters) tokens and [Ellipsis](https://docs.python.org/3/library/constants.html#Ellipsis) are returned using the generic [OP](https://docs.python.org/3/library/token.html#token.OP) token type.
From https://docs.python.org/3/library/tokenize.html

Output:
```
File                                      Token count
------------------------------------------------------
tinygrad/mlops.py                         1925
tinygrad/ops.py                           2220
tinygrad/lazy.py                          3776
tinygrad/tensor.py                        7636
tinygrad/graph.py                         933
tinygrad/helpers.py                       862
tinygrad/jit.py                           625
tinygrad/runtime/lib.py                   462
tinygrad/runtime/ops_metal.py             771
tinygrad/runtime/ops_llvm.py              495
tinygrad/runtime/ops_cpu.py               814
tinygrad/runtime/ops_cuda.py              566
tinygrad/runtime/ops_torch.py             526
tinygrad/runtime/ops_gpu.py               1057
tinygrad/runtime/ops_clang.py             227
tinygrad/codegen/llvmir.py                1825
tinygrad/codegen/linearizer.py            5987
tinygrad/codegen/cstyle.py                1908
tinygrad/nn/optim.py                      929
tinygrad/nn/__init__.py                   1164
tinygrad/nn/image.py                      1457
tinygrad/shape/shapetracker.py            3561
tinygrad/shape/symbolic.py                2601
------------------------------------------------------
Total                                    42327

```

### CODE REVIEW

**Comment by geohot** [comment]
Indentation should be 2 spaces. And can you reverse sort the list?

**Comment by khazit** [comment]
Should be good now

**Comment by truls2592285862** [comment]
Thanks for including a license with your code, it makes it easier to know how I can use it.

**Comment by geohot** [comment]
Cool, it's a good number to look at. 44305 right now, an average of 16.7 / line

**Pull request merged**
