### PR TITLE
Add yolov8 implementation

### PR DESCRIPTION
**Pull request by SehajDxstiny**
usage : python3 ./examples/yolov8.py "https://ultralytics.com/images/bus.jpg" "n" 
note: can put an absolute file path instead of URL and any yolov8 variant in the place of "n".

YOLOv8 implementation and inference:

- [x] Architecture implementation https://github.com/ultralytics/ultralytics/issues/189
- [X] Pre-processing functions  
- [X] Forward Pass + util functions
- [x] Loading pre-trained weights https://github.com/ultralytics/ultralytics
- [x] Loading all v8 variants (n, s, m, l, x) 
- [x] Post processing predictions
- [x] Draw bounding boxes and save results as image 
- [X] Adding tests (full inference)
- [x] Remove torch

### CODE REVIEW

**Comment by geohot** [comment]
Use 2 spaces for indentation. Are there tests? Examples?

**Comment by r3sist-uniq** [comment]
will add tests now.

**Comment by r3sist-uniq** [comment]
TO-DO
- Fix maxpool in the SPPF block (it's supposed to replicate nn.MaxPool2d which pads as well. currently there is 4-5% difference, though visually doesn't make a difference)
- add batch post processing.
- There is some issue in the pre-processing functions. 
- perhaps make NMS in tinygrad (post processing will be much much faster)
- add tests

**Comment by SehajDxstiny** [comment]
TODO for later: 

(these does not affect the results visually)
 1. Fix SPPF minor difference due to maxpool  
 2. AST exp overflow warning while on cpu 
 -----------------------------------------------------
 4.  Make NMS faster (by making in tinygrad)
 5. Add video inference (batch) and webcam support

**Comment by r3sist-uniq** [comment]
@geohot added safetensors

**Comment by wozeparrot** [comment]
You should be able to use `safe_load` in https://github.com/geohot/tinygrad/blob/master/tinygrad/state.py

**Comment by r3sist-uniq** [comment]
> You should be able to use `safe_load` in https://github.com/geohot/tinygrad/blob/master/tinygrad/state.py

coool thanks. it's also faster than the safetensor function.

**Pull request merged**
