### PR TITLE
Llvm int support

### PR DESCRIPTION
**Pull request by dc-dc-dc**
Added llvm int support

split the dtype tests so that int tests are now run for llvm runtime

### CODE REVIEW

**Comment by geohot** [comment]
Hmm, conflicts with your last PR (which I merged)

**Comment by dc-dc-dc** [comment]
rebased and pushed

**Comment by geohot** [comment]
Sweet, thanks. You interested in a $200 int8 LLaMA bounty? Would also involve a quality check on LLaMA for both float16 and int8.

**Comment by dc-dc-dc** [comment]
Sure, is there a issue or pr with more info on the task ?

**Comment by geohot** [comment]
Nope, it's just what's described:
* Get LLaMA 7B running with uint8 weights (leave float16 support too)
* Evaluate both the float16 one and uint8 one with ARC+HellaSwag+MMLU+TruthfulQA and confirm they match https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard
Bounty created and locked to you.

**Pull request merged**
