### PR TITLE
:hammer: refactor register ops

### PR DESCRIPTION
**Pull request by kartik4949**
Refactor registering ops

### CODE REVIEW

**Comment by kartik4949** [comment]
unit test failing because of master!

**Comment by geohot** [comment]
Can you figure out why I can't merge this? Think about dependencies and what extra is.

Also, this isn't the refactor I asked for. Making that a function to save 3 lines is less readable. Move the functionality.

**Comment by kartik4949** [comment]
Sorry i read it wrong in the dynamic registering pr 
Make sense it definitely shouldn't be outside tinygrad 
Will move it!

**Comment by kartik4949** [comment]
@geohot may be below is way too complex

```
class Register(type):                                                        
    def __new__(cls, clsname, bases, clsdict):
        cls = super().__new__(cls, clsname, bases, clsdict)  
        register(clsname.lower(), cls, device=Device.CPU)                        
        return cls                                                                              
class Function(metaclass=Register):  
```
and only problem im having how can i get the device in tensor.py
any idea or should i leave this?

**Comment by Liamdoult** [comment]
Think along the lines of:
``` python
import ops

for name, cls in inspect.getmembers(ops, inspect.isclass):
```

**Comment by kartik4949** [comment]
> Think along the lines of:
> 
> ```python
> import ops_cpu
> 
> for name, cls in inspect.getmembers(ops_cpu, inspect.isclass):
> ```

hmm,
```
import ops_cpu, ops_gpu, ops_ane
.
.
.
def _register(namespace):
    for name, cls in inspect.getmembers(namespace, inspect.isclass):
        if name[0] != "_":  register(name.lower(), cls, device=namespace.DEVICE)
for namespace in [ops_cpu, ops_gpu, ops_ane]:
    _register(namespace)
  
```
we can make DEVICE constant in each file 
@Liamdoult something like this?

**Comment by Liamdoult** [comment]
I think the best implementation would involve something like this at the bottom of `ops_gpu`:
``` python
register(sys.modules[__name__], Device.GPU)
```

**Comment by Liamdoult** [comment]
But this would have less lines:
``` python
try:
  import pyopencl as cl
  # TODO: move this import to require_init_gpu?
  from tinygrad import ops_gpu
  register(ops_gpu, Device.GPU)
  GPU = True
except ImportError:
```

**Comment by kartik4949** [comment]
> But this would have less lines:
> 
> ```python
> try:
>   import pyopencl as cl
>   # TODO: move this import to require_init_gpu?
>   from tinygrad import ops_gpu
>   register(ops_gpu, Device.GPU)
>   GPU = True
> except ImportError:
> ```

agreed I was think to move it as function under tensor.py but as George pointed out it is less readable

> Can you figure out why I can't merge this? Think about dependencies and what extra is.
> 
> Also, this isn't the refactor I asked for. Making that a function to save 3 lines is less readable. Move the functionality.

**Comment by kartik4949** [comment]
> But this would have less lines:
> 
> ```python
> try:
>   import pyopencl as cl
>   # TODO: move this import to require_init_gpu?
>   from tinygrad import ops_gpu
>   register(ops_gpu, Device.GPU)
>   GPU = True
> except ImportError:
> ```

makes sense ..actually done!..
branch ready for merge @geohot

**Comment by kartik4949** [comment]
ready for merge, should have thought about moving it to tensor :(

**Pull request merged**
