### PR TITLE
Added support for strided max & average pooling

### PR DESCRIPTION
**Pull request by skoshx**
This pull request adds support for strided max & average pooling, with a numpy solution. It's not optimal, however I don't know if its possible to do with just reshape ops, so had to resort to it. Only uses the numpy solution if stride is specifically specified.

Alternatively max & avg pooling ops could be first class ops, with CPU & GPU implementations with stride support.

### CODE REVIEW

**Comment by geohot** [comment]
So tinygrad proper can't import from an example!

And does this work on GPU?

**Comment by skoshx** [comment]
Yes, I don't know what I was thinking :D Obviously the "core" should be separated. I added couple fixes so it runs on GPU aswell, that being said, it obviously won't run any faster on GPU, since the pooling is done on CPU by numpy... 

I recall you saying that tinygrad would in the future run on custom accelerated hardware, is this still the case? Will tinygrad be used in production? Because if so, strided max & avg pooling should probably be implemented as standalone ops, to allow for custom accelerators to be added.

**Comment by geohot** [comment]
I have no idea how this works on the GPU. I can't merge this until:
* Tensor doesn't import from extra
* The Tensor ops don't use numpy outside ops_cpu

**Comment by geohot** [comment]
Why did the names change?

**Comment by skoshx** [comment]
@geohot So I thought about backwards compatibility when making max & avg pooling into first class ops, and there are currently 3 options: (1) either we keep the `max_pool2d` function in the tensor class, and from there call the actual CPU/GPU specific functions, or (2) name the classes Max_Pool2d and Avg_Pool2d, to have backwards compatibility, without needing to have a separate function for it in the `Tensor` class, and (3) name it MaxPool2d & AvgPool2d, following the same naming convention as other first class ops, but resulting in breaking changes for tinygrad.

Let me know which solution you think is the best, and I will include it in the next commit.

**Comment by skoshx** [comment]
@geohot I finally got done implementing everything, and as the tests show, it is about 150 lines above the line limit. Even if I changed the `pool2d` to also do the average pooling backwards pass, it still would be more than 90 lines above the line limit. What do you think? (Also I don't know why GPU tests fail, since they pass on my computer)

A couple things:

- I run a software studio [(Skosh)](https://skoshx.com/), and I was checking out your website, and thought that we could pimp out your website for free if you are interested, only thing I would ask for would be a "Made by" link at the bottom, and some goodwill. Same offer goes for Cherry Computer, a revolutionary company needs to have a website that reflects the quality of the company!
- On a more "Open Source Software"-note, I love the idea of Cherry Computer, and would like to contribute as much as possible. I had a couple ideas such as parallel computing to run on multiple GPUs (or Cherry chips), or a PyTorch compatibility layer with functions etc. from PyTorch implemented in Tinygrad, making Tinygrad more PyTorch "compatible". If any of these seem interesting, or if you'd rather have me work on the TODO list instead, just let me know!

**Comment by geohot** [comment]
Hmm, there has to be a cleaner way to do this.

**Comment by skoshx** [comment]
> Hmm, there has to be a cleaner way to do this. Can't merge now, it's over the line limit.

I agree, and tried countless implementations, all of which failed when testing with combinations of asymmetrical kernel sizes and strides where the sliding window would overflow "outside" the input data, I can try to reduce the amount of lines, but I can't think of another way that supports asymmetric strides, which are essential for a deep learning library (needed for YOLO models)

**Comment by geohot** [comment]
So is there a way to separate the stride from the pool?

What if you do a conv first to get the stride, then do the pool?

**Comment by skoshx** [comment]
Seems like an interesting approach, will try it out!

**Comment by geohot** [comment]
Closing, there's a new simpler one.

**Pull request closed without merging**
