### PR TITLE
Some docs regarding functionality

### PR DESCRIPTION
**Pull request by calledit**
This is a short overview of the things that I think are important in tinygrad.
There might be shortcomings in the overview as I do not know every single detail of tinygrad, but I think my outsider perspective might be useful.

### CODE REVIEW

**Comment by geohot** [comment]
I would merge nice docs, but they would have to be a lot higher quality. This isn't bad as notes on the wiki or something though.

**Comment by calledit** [comment]
Yes, needs to be expanded and improved. Think of it as a draft PR.
The GitHub wiki would be a good place for this type of things. If you enable the wiki on the repo, one could work on things there.

**Comment by geohot** [comment]
Wiki should be enabled? I just created a home page

**Comment by calledit** [comment]
I don't see any edit buttons on the wiki. There might be some type of setting somewhere that allows other people to the edit the wiki?

**Comment by geohot** [comment]
Try now

**Comment by calledit** [comment]
Yeah, that worked!

**Pull request closed without merging**
