### PR TITLE
pygame is fine, cv2 can also do the trick

### PR DESCRIPTION
**Pull request by dustcollector12**

### CODE REVIEW

**Comment by marcelbischoff** [comment]
I thought that too and was going to commit the same.

**Comment by dustcollector12** [comment]
Thanks, that's kind.

**Comment by geohot** [comment]
Hmm, I was just going to test the cv2 (I like this if it works), but I don't like the retimg change. I want to display exactly what we are feeding into the net, not precrop.

**Comment by dustcollector12** [comment]
I see the point. I'll try to come up with some more updates later today.

**Comment by dustcollector12** [comment]
Okay, one more attempt. I also thought, it could be a good idea to move the print statements and time measurement into infer and evaluate only model.forward, but wasn't quite sure about this yet.

**Comment by geohot** [comment]
Hmm, no window on my Mac.

**Pull request merged**
