### PR TITLE
RDNA assembly backend ($1000 bounty)

### PR DESCRIPTION
**Pull request by geohot**
`DEBUG=5 RDNA=1 FORWARD_ONLY=1 python3 test/test_ops.py TestOps.test_add` works.

Rough steps:
- [x] Support varying numbers of inputs. (generate that YAML)
- [x] Write register allocator
- [x] Write Symbolic codegen to generate all the indexes.
- [x] Support all the ALU ops.
- [x] Support loops.
- [ ] RDNA backend passes all tests

$1000 bounty if someone gets a working, clean, RDNA3 assembler. Good quality code that passes all the ops tests. If you post a good start and I believe you will finish, I'll lock the bounty for you.

I claimed this bounty myself, the first $1,000 the tiny corp will pay me.

### CODE REVIEW

**Comment by murat8603973081** [comment]
Thank you for being so responsive to issues and pull requests.

**Comment by campbel51838903** [comment]
I'm having trouble getting your code to work, could you help me troubleshoot?

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/codegen/assembly.py             197               0
tinygrad/codegen/linearizer.py             6               0
tinygrad/helpers.py                        3               1
tinygrad/ops.py                            4               4
tinygrad/runtime/ops_gpu.py                2               0
tinygrad/runtime/ops_rdna.py               5               0
tinygrad/tensor.py                         1               1
------------------------------------------------------------
total                                    218               6
------------------------------------------------------------
lines added in the tinygrad folder: 212
```

**Comment by geohot** [comment]
So these shouldn't be new runtimes, just new codegens for GPU and CUDA.

**Comment by geohot** [comment]
Going to merge this, but it doesn't pass the tests yet.

We should look at GEMM and see why it's fast. The dual issue ALU isn't as good as I thought it was, it doesn't allow broadcasts.

**Comment by stalkerg** [comment]
Did you try to compare with Rusticl with ACO or LLVM from Mesa?

**Pull request merged**
