### PR TITLE
fixed 'TypeError: BatchNormalization() got an unexpected keyword argu…

### PR DESCRIPTION
**Pull request by aelqaraoui**
I fixed this error : TypeError: BatchNormalization() got an unexpected keyword argument 'is_test'

opt had 'is_test' key and I removed it.

### CODE REVIEW

**Comment by geohot** [comment]
Does is_test do anything?

**Comment by aelqaraoui** [comment]
is_test shouldn't be passed to real_fxn, I only changed the opt in the function call in case it's used anywhere else.

**Comment by geohot** [comment]
I'm saying, it is being ignored how you are doing it. It can't be a totally meaningless parameter, can it?

**Comment by aelqaraoui** [comment]
I couldn't find it being used anywhere in the code, so I don't know what is used for. Also is it be used if it's an unexpected keyword argument?

**Pull request closed without merging**
