### PR TITLE
Stable Sigmoid op

### PR DESCRIPTION
**Pull request by kartik4949**
@geohot this pr replaces the existing sigmoid with stable sigmoid.
This is a critical fix and this repo needs more attention like overflow and underflow,  e.g in div op.

### CODE REVIEW

**Comment by geohot** [comment]
Looks good, can you fix spaces?

**Comment by kartik4949** [comment]
Yeah , my formatter!

**Comment by geohot** [comment]
Still 4 spaces!

**Comment by kartik4949** [comment]
@geoho done!
sorry my was vi was behaving weird, (new plugins -_-)

**Pull request merged**
