### PR TITLE
Add LAMB optimizer

### PR DESCRIPTION
**Pull request by wozeparrot**
This is the first in what will hopefully be a series of prs to get RNN-T training working.

This adds the [LAMB optimizer](https://arxiv.org/abs/1904.00962) based on the official tensorflow implementation [here](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/optimizers/lamb.py).

I'm not sure what the best way to test this is as pytorch doesn't have LAMB implemented and the implementations that I could find are either [CUDA specific](https://nvidia.github.io/apex/_modules/apex/optimizers/fused_lamb.html) or [broken](https://github.com/jettify/pytorch-optimizer/issues/226). So thats why this is draft for now.

I have tested this on training a small net on MNIST and it does work.

It should also be possible to rewrite AdamW and Adam as functions of LAMB if we wanted to save some lines.

### CODE REVIEW

**Comment by geohot** [comment]
I locked the RNN-T training bounty for you, but will wait on merging this until there's tests. I'm shocked PyTorch still doesn't have LAMB.

Maybe test with something like https://pytorch-optimizer.readthedocs.io/en/latest/_modules/torch_optimizer/lamb.html and add it as an "external" test, which means it doesn't run in CI and can depend on weird things like `pytorch-optimizer`

**Comment by wozeparrot** [comment]
> Maybe test with something like https://pytorch-optimizer.readthedocs.io/en/latest/_modules/torch_optimizer/lamb.html and add it as an "external" test, which means it doesn't run in CI and can depend on weird things like `pytorch-optimizer`

This is the one I linked that is actually broken and doesn't match the official implementation

**Comment by geohot** [comment]
wow what a world. test against tensorflow then?

**Comment by wozeparrot** [comment]
> wow what a world. test against tensorflow then?

Should be fine. Will put it as an external test.

**Comment by wozeparrot** [comment]
Should I also add LARS? I looked through the training reference repo and its only used in one place and in that one place it can also be swapped with SGD.

**Comment by wozeparrot** [comment]
wow this is so annoying even in tensorflow its not official but in an addon package.

**Comment by wozeparrot** [comment]
added an external test against tensorflow and tesnsorflow addons, which btw is also being wound down (https://github.com/tensorflow/addons/issues/2807), so thats great.

**Comment by geohot** [comment]
Looks like we'll have the only working LAMB then.

**Comment by geohot** [comment]
Hmm actually this fails on my M1:
```
kafka@tubby:~/fun/tinygrad$ python3 test/external/external_test_optim.py
/opt/homebrew/lib/python3.10/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
Metal device set to: Apple M1 Max

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB

/opt/homebrew/lib/python3.10/site-packages/tensorflow_addons/optimizers/lamb.py:90: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)
F...
======================================================================
FAIL: test_lamb (__main__.ExternalTestOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kafka/fun/tinygrad/test/external/external_test_optim.py", line 68, in test_lamb
    def test_lamb(self): self._test_lamb(1, {'lr': 0.001}, 1e-5, 0)
  File "/Users/kafka/fun/tinygrad/test/external/external_test_optim.py", line 66, in _test_lamb
    def _test_lamb(self, steps, opts, atol, rtol): self._test_optim(LAMB, tfa.optimizers.LAMB, steps, opts, atol, rtol)
  File "/Users/kafka/fun/tinygrad/test/external/external_test_optim.py", line 64, in _test_optim
    np.testing.assert_allclose(x, y, atol=atol, rtol=rtol)
  File "/opt/homebrew/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/opt/homebrew/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 768, in assert_array_compare
    flagged = func_assert_same_pos(x, y, func=isnan, hasval='nan')
  File "/opt/homebrew/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 745, in func_assert_same_pos
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0, atol=1e-05

x and y nan location mismatch:
 x: array([[      nan, -0.489293, -0.320825, -1.754089]], dtype=float32)
 y: array([[-0.702197, -0.489293, -0.320825, -1.754089]], dtype=float32)

----------------------------------------------------------------------
Ran 4 tests in 0.616s

FAILED (failures=1)
```

**Comment by geohot** [comment]
Also, there's no test with the `adam` flag.

**Comment by geohot** [comment]
Interesting, it passes with CPU, TORCH, LLVM, and GPU, but fails with METAL. Do you have a Mac to investigate?

**Comment by wozeparrot** [comment]
I don't have a mac to test with. I'll open up a pr for the adam flag or maybe we just remove it. I was intending to rewrite adam and adamw as functions of lamb to shorten the line count.

**Pull request merged**
