### PR TITLE
Ci pypi release automation

### PR DESCRIPTION
**Pull request by Liamdoult**
Automatically release an updated version of tinygrad to PyPI by creating a release on github.

@geohot You will have to set repo secrets.

gotcha: The GitHub release version/tag does not effect the version uploaded to PyPI, this is based on `setup.py`. So this should be updated prior to creating the release.

### CODE REVIEW

**Comment by geohot** [comment]
I still want this, just need to find the time to set it up.

**Comment by Liamdoult** [comment]
@geohot  ping

**Comment by Polydynamical** [comment]
bump

**Comment by geohot** [comment]
Finally set this up!

**Pull request merged**
