### PR TITLE
Let compiler optimize division by 1, broadcasting 1s at the start

### PR DESCRIPTION
**Pull request by adamritter**

### CODE REVIEW

**Comment by adamritter** [comment]
(4, 32, 112, 112) != (1, 32, 1, 1) needs to be supported as well, I'll look into the easiest way to modify the code for that case

**Comment by geohot** [comment]
Hmm, this is rebuilding the kernel based on the shape

**Comment by ryanneph** [comment]
Recompiling the kernels will likely incur a high cost, so we don’t want to do it every time the op is called.

Aside: The fix for the sometimes failing test_conv2d grad check is to increase the grad_rtol=1e-5. Since it’s saved in the test definition, we can see by inspection that the backward accuracy for conv2d (on GPU) is a bit lower than desired. It’s probably a compounded truncation error since there are so many nested loops and we are working with 32 bit precision on the GPU.

**Comment by adamritter** [comment]
> Hmm, this is rebuilding the kernel based on the shape
Is that a problem? Division is inefficient on GPUs

**Comment by adamritter** [comment]
> Aside: The fix for the sometimes failing test_conv2d grad check is to relax the tolerance to grad_rtol=1e-5. Since it’s saved in the test definition, we can see by inspection that the backward accuracy for conv2d (on GPU) is a bit lower than desired. It’s probably a compounded truncation error since there are so many nested loops and we are working with 32 bit precision on the GPU.

I agree with you, but that still doesn't fix the flakiness of the test, which is a bigger problem than setting the precision. It's OK the test to fail, but when I'm running multiple times on the same machine and get different results, that makes developing hard.

**Comment by ryanneph** [comment]
> > Aside: The fix for the sometimes failing test_conv2d grad check is to relax the tolerance to grad_rtol=1e-5. Since it’s saved in the test definition, we can see by inspection that the backward accuracy for conv2d (on GPU) is a bit lower than desired. It’s probably a compounded truncation error since there are so many nested loops and we are working with 32 bit precision on the GPU.
> 
> I agree with you, but that still doesn't fix the flakiness of the test, which is a bigger problem than setting the precision. It's OK the test to fail, but when I'm running multiple times on the same machine and get different results, that makes developing hard.

Does grad_rtol need to be further relaxed then? Having a test that passes every time with known accuracy expectations is better than one that passes sometimes with strict accuracy expectations. Or is there some other issue?

**Comment by adamritter** [comment]
> Recompiling the kernels will likely incur a high cost, so we don’t want to do it every time the op is called.

It has to be compiled only for the first run for each operation, so when training the efficientnet, the training itself will be more efficient. Of course benchmarking is needed to see if the kernel compilation time is worth it for each broadcasting shape.

**Pull request closed without merging**
