### PR TITLE
Abstracted tensor.py helper functions

### PR DESCRIPTION
**Pull request by catasaurus**
Abstracted tensor.py helper functions for creating a tensor of shape size and a certain fill.

### CODE REVIEW

**Comment by geohot** [comment]
If you want to add functions to core, you have to match a torch API.

This is not a refactor, it adds 3 lines.

Perhaps https://pytorch.org/docs/stable/generated/torch.full.html

**Comment by catasaurus** [comment]
Oh, ok. Would it work if I renamed it to `full`? Also it was not meant to be a refactor. I just thought it was redundant and that it would also be useful to have a function that removes the need for `zeros` and `ones`.

**Comment by catasaurus** [comment]
renamed it.

**Comment by geohot** [comment]
It's not just the name. It needs to match the torch function, which that does not.

**Comment by catasaurus** [comment]
Oh, the exact parameters?

**Comment by catasaurus** [comment]
Ok, I changed it. Also, what do you think of deleting zeros, ones, zeros_like, and empty. They are just eight lines of functions that do the equivalent of having a different function to print hello and one to print no when you have one that can print almost anything supported by the OS, or full.

**Pull request closed without merging**
