### PR TITLE
Fix ResNet Kernel Fusion (from bounty)

### PR DESCRIPTION
**Pull request by mrdaybird**
After the fix, running `test_resnet` gives the following output:
```
cache: entering
cache: exiting with size 26 allowed 31
```
Before the current change, it was showing 29(instead of 26)
Please confirm if this is the correct fix.

### CODE REVIEW

**Comment by geohot** [comment]
Hmm, I don't think so, I don't understand what this does. Is the output of the resnet still correct?

The issue has to do with op fusion, run the resnet with `GRAPH=1` to see the issue.

**Comment by geohot** [comment]
I will lock the bounty for you though as long as you are working on it.

**Comment by mrdaybird** [comment]
Hey @geohot!
Can you tell me what your concern was with "NOTE" that you have written at [L37 in lazy.py](https://github.com/geohot/tinygrad/blob/2fd2fb6380ef41bfb36cd370f2437dae282813ae/tinygrad/lazy.py#L37)? 
To be exact, my question is, what problems could arise when handling "psrcs" whose len>1 ?

**Comment by geohot** [comment]
You have to check the dep order. 

```
A
|---|
B    |
|---|
C
```

You have to fuse C with B and not A.

**Comment by mrdaybird** [comment]
Hello again @geohot !
I would argue that the case that you mentioned have doesn't ever occur. 

**Explanation:**  The _psrcs_ list contains only elements that have atmost one children, look at condition at the end of line 34 of _lazy.py_(below). So, if a source has multiple dependency it is not getting included for optimization.
https://github.com/geohot/tinygrad/blob/2fd2fb6380ef41bfb36cd370f2437dae282813ae/tinygrad/lazy.py#L34 

Now after changing the code to select the first reduce op from _psrcs_, I ran the tests, from the test_suite and some of my own, and they passed and  I see nothing out of the ordinary. There is no change in numeric values before and after. 
It looks like the selecting any one of the reduce_op for fusion will work. What do you think?

**Comment by geohot** [comment]
Hmm, so there had to be some reason I didn't do that...but the tests do pass and the resnet is 26....

Give me today to find it, if I can't, we'll merge and you just got $100 for a character 🤣

**Comment by geohot** [comment]
Congrats! There probably was some reason for this, but I can't find it now.

Either post here or e-mail george@tinygrad.org to claim bounty. Can pay with PayPal or lmk if you prefer something else.

**Comment by mrdaybird** [comment]
:smiley: Yay!
Though in the end the final change was 1 character, it took hundreds of lines of code trying to understand what actually happening behind the scenes as it was a completely new project to me. Regardless, it was not easy :sweat_smile:, but it was fun!  

Regarding the bounty, I will hit you with an email soon!

Also, I was already interested with the other bounty about xNorm fusion and it is a problem I am very eager to solve, but I will give myself a few days time to figure out if I can actually do it in a reasonable period of time(well every problem is solvable by anyone if not bound by time, if it has a solution though).

**Comment by geohot** [comment]
Hehe, yea I'm joking about the one character thing. The value is in finding it and testing it!

**Pull request merged**
