### PR TITLE
Dynamically register ops to Tensor

### PR DESCRIPTION
**Pull request by Liamdoult**
This saves lines. And reduces redundant repetition.

### CODE REVIEW

**Comment by Liamdoult** [comment]
Tests fail because of missing master!

**Comment by Liamdoult** [comment]
+20 lines ! :D

**Comment by geohot** [comment]
Finally, a refactor of this I can merge! I'd consider moving the sys inspect stuff out to tensor.py, that way you only need it once.

**Comment by kartik4949** [comment]
@geohot say nno more checkout #233

**Pull request merged**
