### PR TITLE
Cuda accelerator

### PR DESCRIPTION
**Pull request by martinloretzzz**
Updated the CUDA accelerator to use tinygrad llops(more like rebuilt it from scratch).
All tests pass (CUDA=1 python -m pytest -s -v), should we add it to the CI?
It still needs to be faster (elementwise are around 2 times slower than GPU, small conv's equally fast, big conv's and gemm way slower than GPU)

### CODE REVIEW

**Comment by geohot** [comment]
Cool! Check out the new GPU port, I think there's a lot of overlap there.

Is CUDA faster than OpenCL on NVIDIA? Can you show that?

**Comment by martinloretzzz** [comment]
It's not fast yet, it works and all tests passed.
I just did it for the challenge, building some cool stuff. It was also my first time using CUDA.
It uses parallel sum reduction for reduce ops, but I think this actually hurts performance more than increases it. (Many threads that do not much work, from this [tutorial](https://www.youtube.com/watch?v=bpbit8SPMxU)).
Memory accesses aren't optimised in any way, just using the expression from the shapetracker.

That's the results of test_speed_v_torch.py between totch CUDA and this CUDA accelerator.
image

What's the plan for CUDA? Build it like the gpu ops or use Triton?
Looked up what Triton is yesterday, and it seems really cool and a lot easier to make a fast CUDA backend.

**Comment by geohot** [comment]
Yea, see my starting PR on that. I think Triton is the way to go for CUDA, want to try?

**Comment by martinloretzzz** [comment]
Yeah sure

**Comment by martinloretzzz** [comment]
It sounds like a cool challenge.
I will have to see how much time I have in the near future, but it will work out somehow.

**Comment by geohot** [comment]
CUDA is now upstream, reusing 95% of the ops_gpu backend. Going to close this.

**Pull request closed without merging**
