### PR TITLE
Refactor code_for_op to accept a dtype

### PR DESCRIPTION
**Pull request by Qazalin**
The immediate user is UnaryOps.NEG for the bool dtype.

### CODE REVIEW

**Comment by Qazalin** [comment]
openpilot flakey again, maybe we should do a retry? https://github.com/tinygrad/tinygrad/actions/runs/7065373654/job/19235253307?pr=2555#step:15:602

**Comment by Qazalin** [comment]
openpilot flaky again, maybe we should do a retry? https://github.com/tinygrad/tinygrad/actions/runs/7065373654/job/19235253307?pr=2555#step:15:602

**Comment by geohot** [comment]
Two things:

1. As I mentioned in the other PR, which param does this dtype apply to?
2. I don't think a retry is a good choice. Can you remove the non determinism?

**Comment by Qazalin** [comment]
both inputs and the final output, because inputs always get upcasted.
the exception here is TernayOps.WHERE, there is always one bool and two vars of the same dtype, in that case, the two vars and the return value have the same dtype

**Pull request merged**
