### PR TITLE
Onnx Simplifications

### PR DESCRIPTION
**Pull request by eichenroth**
Small improvements to the ONNX executor.

- typing
- understandable code
- less lines

No additional tests got fixed

### CODE REVIEW

**Comment by geohot** [comment]
Is all this changed code well tested in CI?

**Comment by eichenroth** [comment]
I see your point, but I think we have an exception here.

The only file that is touched is `onnx.py` - which is still WIP and very buggy in itself. I cannot prove that I did not introduce any bugs, however the number of failed onnx tests did not go up - therefore I think I did not make it worse.

Would you merge, if I fix some onnx tests with this PR?

**Comment by geohot** [comment]
Even better, test `onnx.py`

**Comment by eichenroth** [comment]
😄 that sounds reasonable

**Pull request closed without merging**
