### PR TITLE
add Upsample nearest

### PR DESCRIPTION
**Pull request by dc-dc-dc**
only added nearest

### CODE REVIEW

**Comment by geohot** [comment]
Where is this used? Before promoting stuff to nn, I want to see at least 3 models using it.

**Comment by dc-dc-dc** [comment]
should be needed for retina-net on the pyramid features, but we can leave it open for now to meet the 3 model requirement

**Comment by geohot** [comment]
For now it probably belongs as part of retinanet.

**Comment by geohot** [comment]
Going to close this, merge with retinanet?

**Pull request closed without merging**
