### PR TITLE
feat: :sparkles: Sub-Pixel Convolutional

### PR DESCRIPTION
**Pull request by aabbdev**
Learns a set of upscaling filters to transform low-resolution feature maps into high-resolution outputs by rearranging sub-pixels spatially

### CODE REVIEW

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/nn/image.py                      18               0
tinygrad/tensor.py                         3               1
------------------------------------------------------------
total                                     21               1
------------------------------------------------------------
lines added in the tinygrad folder: 20
```

**Comment by jla524** [comment]
Can you add some tests?

**Comment by geohot** [comment]
What models is this used in? I've never seen it before.

Also, like @jla524 said, all added features need tests. And I'm not sure this belongs in main tinygrad, it's +28 lines.

**Comment by aabbdev** [comment]
Hello
I didn't have time this morning lol
This layer is used in the majority of SOTA super-resolution models (30% according to statistics). It was introduced by ESPCN.
I haven't finished my PR, I'll add more tests, and I wanted to add a real model example.

docs:
https://paperswithcode.com/method/pixelshuffle
https://medium.com/@hirotoschwert/introduction-to-deep-super-resolution-c052d84ce8cf

**Comment by wozeparrot** [comment]
At the very least, I don't think this belongs in `nn`.

**Comment by aabbdev** [comment]
as you wish, that's how it is in pytorch. I thought I heard you say you wanted to keep a similar api

**Comment by aabbdev** [comment]
I missed an rebase, I made a mess I will cleanup

**Comment by aabbdev** [comment]
I added tests

**Comment by jla524** [comment]
> as you wish, that's how it is in pytorch. I thought I heard you say you wanted to keep a similar api
> 
> https://pytorch.org/docs/stable/generated/torch.nn.PixelShuffle.html

We want to keep the interface similar. At the same time, we really want to keep tinygrad minimal.

If these layers are only used in one example, then I suggest to move the code to the same file as the example. So everything goes in `examples/espcn.py` or `models/espcn.py`.

**Comment by aabbdev** [comment]
I totally understand your point of view,
you don't want to implement things that are rarely used or "fashionable" but PixelShuffle is an essential building block for super-resolution models.
From my point of view, your logic of minimalism should be on the interface -> backend side only,
PixelShuffle reuses existing functions it doesn't need to modify backends, or add a new ops.

user engineers' point of view :
Ease of model creation

integrator engineers' viewpoint :
Make it easier to implement their accelerator/platform inside the library to run the models.

In this logic, I'm only improving the user experience without touching the integration.

Besides, letting users implement PixelShuffle themselves, however simple, can lead to bugs. For a long time, PixelShuffle didn't work properly in Pytorch, until it caused problems with the ONNX runtime.

Capture d’écran 2023-06-25 à 11 18 40
Capture d’écran 2023-06-25 à 11 18 14

**Comment by geohot** [comment]
Closing, citing @jla524's last post. If operators are only used in one or two models, they belong in the model itself, not core tinygrad.

**Pull request closed without merging**
