### PR TITLE
added steps and SGD+momentum

### PR DESCRIPTION
**Pull request by EduardoPach**
Added more than one step for Optimizers tests and create a new SGD with momentum test.

### CODE REVIEW

**Comment by geohot** [comment]
Does it pass? :)

**Comment by EduardoPach** [comment]
@geohot  it did! And what a blazing-fast response I might say haha

**Comment by geohot** [comment]
Hmm, why do #552 and #553 fail?

**Comment by EduardoPach** [comment]
Fixed the testing, but plain SGD is not working. It works when the number of steps is low. I'll try to figure it out later, since is quite late here already

**Comment by geohot** [comment]
Please reopen if you fix it

**Pull request closed without merging**
