### PR TITLE
Add tests for casting

### PR DESCRIPTION
**Pull request by jla524**

### CODE REVIEW

**Comment by jla524** [comment]
This is failing with TORCH=1
```
a = Tensor([[1,2],[3,4]], dtype=dtypes.float16)
b = Tensor.eye(2, dtype=dtypes.float32)
c = a@b
print(c.numpy())
```

**Comment by jla524** [comment]
Looks like PyTorch doesn't support this kind of operation. I'll skip the test for now.
```
>>> a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float16)
>>> b = torch.eye(2, dtype=torch.float32)
>>> a @ b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
```

Interestingly, this works with TORCH=1
```
>>> from tinygrad.tensor import Tensor
>>> from tinygrad.helpers import dtypes
>>> a = Tensor([[1,2],[3,4]], dtype=dtypes.float32)
>>> b = Tensor.eye(2, dtype=dtypes.float16)
>>> c = a @ b
>>> c.numpy()
array([[1., 2.],
       [3., 4.]], dtype=float32)
```

**Comment by geohot** [comment]
Why is it failing in torch?

**Comment by geohot** [comment]
Sounds like the bug should be fixed :)

**Comment by jla524** [comment]
I looked at the ops and found that reshape is missing in torch. All the other backends have it as the last op.
`LazyOp(op=<MovementOps.RESHAPE: 1>, src=(<LB (2, 2, 1) dtypes.float op:buffer<4, dtypes.float> st:ShapeTracker(shape=(2, 2, 1), views=[View((2, 2, 1), (2, 1, 0), 0)])>,), arg=(2, 2))`

**Comment by jla524** [comment]
I looked at the ops and noticed this reshape is missing in torch. All the other backends have it as the last op.
`LazyOp(op=<MovementOps.RESHAPE: 1>, src=(<LB (2, 2, 1) dtypes.float op:buffer<4, dtypes.float> st:ShapeTracker(shape=(2, 2, 1), views=[View((2, 2, 1), (2, 1, 0), 0)])>,), arg=(2, 2))`

**Pull request merged**
