### PR TITLE
tanh, sigmoid with negative values

### PR DESCRIPTION
**Pull request by f0ti**

### CODE REVIEW

**Comment by geohot** [comment]
Is there an easy way to write this using ops we already have, like div and mean?

**Comment by f0ti** [comment]
I mean there is also np.tanh()

**Comment by geohot** [comment]
No, I mean look in the Tensor class where mean and sqrt are. Currently if I merge this, the tests will fail on the GPU. Can you write it in terms of Tensor ops?

**Comment by geohot** [comment]
https://brenocon.com/blog/2013/10/tanh-is-a-rescaled-logistic-sigmoid-function/

**Pull request closed without merging**
