### PR TITLE
Test split

### LINKED ISSUE #227: Split CPU and GPU tests in CI
They should get different checkmarks.

### PR DESCRIPTION
**Pull request by Liamdoult**
Closes #227

### CODE REVIEW

**Comment by Liamdoult** [comment]
GPU is failing due to master branch, not test suite.

**Comment by geohot** [comment]
This is quite complex. What if we just have GPU=1 make the default tensor GPU, and delete the device specific test code.

**Comment by Liamdoult** [comment]
@geohot, Do you want me to add `GPU=1` as a configuration for the tensor class itself or just the tests?

**Comment by geohot** [comment]
Nice!

**Pull request merged**
