### PR TITLE
replaced os.getenv with helper function

### PR DESCRIPTION
**Pull request by dc-dc-dc**
replaces os.getenv with get_prop helper function, default return is 0 due to popularity 

addresses #499

### CODE REVIEW

**Comment by geohot** [comment]
Hmm, maybe name it "getenv"? get_prop isn't a descriptive name.

And for the places where it's used as "False" isn't 0 fine?

**Comment by dc-dc-dc** [comment]
switched to the getenv function you added in the latest commit

I used False to match the previous value types, but didnt see any cases where we cant just use 0 so using that as the default to stay consistent

**Comment by geohot** [comment]
Tests failing

**Comment by geohot** [comment]
Ended up merging #508, but this one looks good too!

**Pull request closed without merging**
