### PR TITLE
Add .linspace()

### PR DESCRIPTION
**Pull request by xl0**
More from #861

### CODE REVIEW

**Comment by jla524** [comment]
Looks good! Do you want to add some tests?

**Comment by xl0** [comment]
@jla524 , do we have a test-it-all policy? I can add it, but also it just calls np.
I think the test should be added when we move it away from NumPy because then the test writers will have a better feel of the corner cases.

**Comment by tinyb0t** [comment]
Changes made in `tinygrad/`:
```
------------------------------------------------------------
files                             insertions       deletions
------------------------------------------------------------
tinygrad/tensor.py                         2               0
------------------------------------------------------------
lines added in the tinygrad folder: 2
```

**Comment by geohot** [comment]
Calling numpy is bad. Really the numpy calls should be moved to a special section and should eventually all be removed.

Also, I have never used `linspace` If you insist on it, it must be an "hlop"

**Comment by xl0** [comment]
I will look into how to rewrite `linspace` (and `arange` ?) without numpy as an exercise.

**Pull request closed without merging**
