### PR TITLE
onnx if op

### PR DESCRIPTION
**Pull request by rouseabout**
use [diff -w](https://github.com/geohot/tinygrad/commit/f13c2a996099a738221a4d04de2e15432d45df83?w=1) to see run_onnx changes

test/external/external_test_onnx_backend.py:

before:
167 failed, 645 passed, 1822 skipped, 1 warning in 28.40s 

after:
167 failed, 646 passed, 1821 skipped, 1 warning in 28.58s

### CODE REVIEW

**Comment by geohot** [comment]
Tests failing. Don't mix large whitespace changes and functional changes.

**Comment by geohot** [comment]
Still a massive change...why?

**Comment by rouseabout** [comment]
Indentation. Alternative approach, say moving the op eval loop out of run_onnx scope, will incur more changes.

**Comment by geohot** [comment]
Like I said, don't mix large whitespace changes and functional changes.

**Pull request closed without merging**
