### PR TITLE
make maximum split the grad like torch when equal

### PR DESCRIPTION
**Pull request by worldwalker2000**

### CODE REVIEW

**Comment by geohot** [comment]
Cool! Can you add a test?

**Comment by geohot** [comment]
Can the `eq.const_like(2).binary_op(BinaryOps.SUB, eq).binary_op(BinaryOps.DIV, eq.const_like(2))` be only written once?

The function isn't called if no shards are needed, so don't worry about that.

**Comment by geohot** [comment]
Cool, will merge if tests pass

**Comment by worldwalker2000** [comment]
In the failing test a comment reads "# TODO: this should be 4, but the sum output child stays around" and because doing the grad split requires and extra sum op with ".binary_op(BinaryOps.ADD, eq)" there is one more "sum output child" that gets left around. So I have added an 8 to the possible values for "len(GlobalCounters.cache)"

**Pull request merged**
