### PR TITLE
Add AvgPool2d as a layer

### PR DESCRIPTION
**Pull request by jla524**

### CODE REVIEW

**Comment by geohot** [comment]
Hmm, why? This is in yolo and isn't used.

**Comment by jla524** [comment]
I wanted to use it for [resnet](https://github.com/geohot/tinygrad/blob/8835df7a5cd8222e7023c24a89526b731f87501c/models/resnet.py#L99). Is there a better place to store this?

**Comment by geohot** [comment]
Why is this a class at all? It has no state

**Comment by jla524** [comment]
It matches the implementation in PyTorch, but I agree that it doesn't need to be a class

**Comment by geohot** [comment]
One of the reasons tinygrad is better than PyTorch :)

Stateless classes are dumb.

**Comment by jla524** [comment]
Understood. Since MaxPool2d also has no state, I suggest to remove it from yolo.

**Comment by geohot** [comment]
That yolo code is quite bloated tbh

**Pull request closed without merging**
