### PR TITLE
use numba to double conv speed

### PR DESCRIPTION
**Pull request by geohot**
Maybe merge, idk? I don't like the dep and more code

### CODE REVIEW

**Comment by adriangb** [comment]
just curious, how did you benchmark the perf improvement? I'm seeing a perf degradation, but that could just be a constant term.

also, given that this did get merged, any interest in doing:
```python3
try:
  from numba import jit
except ImportError:
  jit = lambda f, *args, **kwargs: f  # return just the function

...

class Conv2D(Function):
  @jit(cache=True)
  def inner_forward(x, w):
    ...
```

So that at least you save a jit compile if it gets run without code changes. Could also enable usage of other numba options (if they improve performance).

**Comment by EWouters** [comment]
Nice to see numba here, it can speed up this code a lot potentially. The main objective of tinygrad doesn't seem to be speed, but rather simplicity and education. However, a large speed up with some simple decorators sounds good to me.

Keep in mind that "premature optimization is the root of all evil" — Knuth.

Having said that, the `jit(cache=True)` should only have a small impact on overall runtime. In cases where it matters you probably shouldn't use numba at all*. What would probably make a difference is using `njit(parallel=True)` and replacing the `range(...)` functions with numba's `drange(...)` or, to keep things easy to write and hard to debug just do `range = numba.drange` if numba can be imported (similar to how you circumvented import errors in your last comment).

* the cache feature can be useful to speed up unit tests.

**Comment by adriangb** [comment]
I think George removed numba now. But I had tested and indeed with the above method you _could_ do:

```python3
try:
  from numba import jit, prange
except ImportError:
  jit = lambda f, *args, **kwargs: f  # return just the function
  prange = range
...

class Conv2D(Function):
  @jit(parallel=True)
  def inner_forward(x, w):
    for ... in prange(...):
       ...
```

But I totally agree on not prematurely optimizing/adding complexity. I'm guessing numba is now gone due to not improving performance and/or adding complexity (at least from the learning side of things).

**Comment by EWouters** [comment]
Ok, fair enough, this might come back at some point.

Just a note about the example, it should be `range = prange`, that way you can leave the `range` calls in the code unmodified.

**Pull request merged**
